(function(){'use strict';var m=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},p=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},q=p(this),r=function(a,b){if(b)a:{var c=q;a=a.split(".");for(var d=
0;d<a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&m(c,a,{configurable:!0,writable:!0,value:b})}};r("globalThis",function(a){return a||q});
r("String.prototype.matchAll",function(a){return a?a:function(b){if(b instanceof RegExp&&!b.global)throw new TypeError("RegExp passed into String.prototype.matchAll() must have global tag.");var c=new RegExp(b,b instanceof RegExp?void 0:"g"),d=this,f=!1,e={next:function(){if(f)return{value:void 0,done:!0};var k=c.exec(d);if(!k)return f=!0,{value:void 0,done:!0};k[0]===""&&(c.lastIndex+=1);return{value:k,done:!1}}};e[Symbol.iterator]=function(){return e};return e}});function t(a){var b,c=!1;return async()=>{if(c)return b;b=await a();c=!0;return b}}function u(a){return[...a.querySelectorAll("script")].filter(b=>b.src.includes("googletagmanager.com/gtag/js")||b.src.includes("googletagmanager.com/gtm.js")||b.src.includes("google.com/gtag/js")||b.src.includes("google.com/gtm.js")||b.innerText.includes("google_tags_first_party"))};var v={type:5},w=class{constructor(a){this.g=a;this.B=async()=>{try{if((await this.g.fetch("https://www.googletagmanager.com/gtag/js?id=DUMMY",{method:"HEAD",mode:"no-cors",cache:"no-store"})).redirected)return v;let b=await (await this.g.fetch("https://www.googletagmanager.com/gtag/js?id=DUMMY")).text();return["DUMMY","google_tag_data","google_tag_manager","/debug/bootstrap?id="].every(c=>b.includes(c))?null:v}catch(b){return v}};this.h=t(this.B)}init(){}destroy(){}};var x={axeptioSDK:17,tC:8,cmplz_set_consent:15,cmpmngr:4,Cookiebot:3,cookiefirst_show_settings:16,cookiehub:22,CookieInformation:9,CLI:20,Osano:10,SP_SCRIPT_CONF:19,SDDAN:14,Termly:12,OneTrust:6,UC_UI:2,cookieyes:11,Didomi:7,TrustArc:13,CookieScript:18,Iubenda:5},y=class{constructor(a){this.g=a}init(){}async h(){var a=[],b=this.g;for(let c in x)b[c]!==void 0&&a.push(x[c]);return a.length>0?{type:6,detectedCmps:a}:null}destroy(){}};var z=class{constructor(a){this.g=a;this.violations=[];this.K=b=>{this.violations.push(b)}}init(){this.g.addEventListener("securitypolicyviolation",this.K)}async h(){return this.violations.filter(a=>a.blockedURI.includes("googletagmanager.com/gtag/js")||a.blockedURI.includes("googletagmanager.com/gtm.js")||a.blockedURI.includes("google.com/gtag/js")||a.blockedURI.includes("google.com/gtm.js")).length>0?{type:9,blockedUrls:this.violations.map(a=>a.blockedURI),violatedDirectives:this.violations.map(a=>
a.violatedDirective)}:null}destroy(){this.violations=[];this.g.removeEventListener("securitypolicyviolation",this.K)}};function A(a){var b=B(a),c=C(a,b),d=a.src,f=a.innerText;if(b===0)return[{l:!1,snippetType:b,errorType:1,scriptSrc:d,scriptContent:f}];if(b===4)return c.map(e=>({l:!1,snippetType:b,tagId:e,errorType:3,scriptSrc:d,scriptContent:f}));a=[];for(let e of c)e&&e.startsWith("GTM-")||D(e)?b===1&&e&&e.startsWith("GTM-")?a.push({l:!1,snippetType:b,tagId:e,errorType:2,scriptSrc:d,scriptContent:f}):b===2&&D(e)&&a.push({l:!1,snippetType:b,tagId:e,errorType:2,scriptSrc:d,scriptContent:f}):a.push({l:!1,snippetType:b,
tagId:e,errorType:3,scriptSrc:d,scriptContent:f});return a.length?a:c.map(e=>({l:!0,snippetType:b,tagId:e,scriptSrc:d,scriptContent:f}))}function B(a){return a.src.includes("googletagmanager.com/gtag/js")||a.src.includes("google.com/gtag/js")?1:a.src.includes("googletagmanager.com/gtm.js?")||a.src.includes("google.com/gtm.js")?2:a.innerText.includes("google_tags_first_party")?E(a).length>0?3:4:0}
function C(a,b){if(b===1||b===2){a:{try{let d;var c=(d=(new URL(a.src)).searchParams.get("id"))!=null?d:void 0;break a}catch(d){}c=void 0}return(a=c)?[a]:[]}return E(a)}function D(a){return a?a.startsWith("G-")||a.startsWith("GT-")||a.startsWith("AW-")||a.startsWith("FL-")||a.startsWith("GA-")||a.startsWith("DC-"):!1}
function E(a){var b=a.innerText.match(/window,'([^&]+)','google_tags_first_party'/);if(b)return[b[1]];b=a.innerText.match(/window,\[(.*?)\],'google_tags_first_party'/);a=[];if(b&&b[1]){b=b[1].matchAll(/'([^']+)'/g);for(let c of b)a.push(c[1])}return a};var F=class{constructor(a){this.g=a}init(){}async h(){var a=u(this.g.document);for(let b of a){a=A(b);for(let c of a)if(!c.l)return{type:8,snippetType:c.snippetType,tagId:c.tagId,errorType:c.errorType,scriptSrc:c.scriptSrc,scriptContent:c.scriptContent}}return null}destroy(){}};var G=class{constructor(a){this.g=a}init(){}async h(){var a={type:3};return this.g.navigator.onLine?null:a}destroy(){}};var J=class{constructor(a){this.g=a}init(){}async h(){var a=this.g;a=!!(a["google.tagmanager.debugui2.queue"]||a["google.tagmanager.ta.prodqueue"]||a.google_tag_data);var b=u(this.g.document);return a||b.length!==0?null:{type:4}}destroy(){}};var aa=class{constructor(a){this.g=a;this.B=async()=>await K(this.g.location.href)?null:{type:7};this.h=t(this.B)}init(){}destroy(){}};async function K(a){try{return(await fetch(a,{method:"HEAD",mode:"no-cors",cache:"no-store"})).status<400}catch(b){return!1}};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ba=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(let c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var ca=class{constructor(){this.M=void 0;this.m=!1;this.o=[]}addListener(a){if(this.m)return()=>{};this.o.push(a);return()=>{this.removeListener(a)}}destroy(){this.m||(this.o=[],this.M&&this.M(),this.m=!0)}removeListener(a){if(!this.m){var b=this.o;a=ba(b,a);a>=0&&Array.prototype.splice.call(b,a,1)}}};var L=function(a){a.v=a.v.then(async()=>{var b=await da(a),c;if((c=a.u)!=null&&!c.m){c=[...c.o];for(let d=0;d<c.length;d++)try{c[d](b)}catch(f){console.log("Event listener failed",f)}}})},M=function(a){if(!a.I&&(a.g.document.head||a.g.document.body)){a.I=!0;a.O=Date.now();for(let b of a.D)b.j!==void 0?b.j.init():b.init();a.P=setInterval(()=>{L(a)},1E3);L(a)}},ea=function(a,b){a.u.addListener(b)},da=async function(a){return{issues:(await Promise.all(a.D.map(b=>b.j!==void 0?b.timeoutMs&&Date.now()-
a.O<b.timeoutMs?Promise.resolve(null):b.j.h():b.h()))).filter(b=>b!==null),pageUrl:a.g.location.href}},fa=class{constructor(a){this.g=a;this.u=new ca;this.I=!1;this.O=0;this.v=Promise.resolve();this.D=[new G(a),new F(a),new aa(a),new z(a),new w(a),new y(a),{j:new J(a),timeoutMs:5E3}]}destroy(){var a;(a=this.u)==null||a.destroy();this.u=void 0;this.v=Promise.resolve();clearInterval(this.P);for(let b of this.D)b.j!==void 0?b.j.init():b.init()}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var N=globalThis.trustedTypes,O;function ha(){var a=null;if(!N)return a;try{let b=c=>c;a=N.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var ia=class{constructor(a){this.U=a}toString(){return this.U+""}};function P(a){var b;O===void 0&&(O=ha());a=(b=O)?b.createScriptURL(a):a;return new ia(a)};function Q(a,...b){if(b.length===0)return P(a[0]);var c=a[0];for(let d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return P(c)};function R(a){a.endsWith("/")}Q`cs/ta/tag_assistant_api_bin.js`;Q`cs/ta/content_script_bin.js`;Q`cs/ta/start_debug_content_script_bin.js`;Q`cs/ta/start_prod_debug_content_script_bin.js`;Q`cs/gf/guided_flows_content_script_bin.js`;R("https://tagassistant.google.com/guided_flows/open");R("https://tagassistant.google.com");R("https://tagassistant.google.com/embedded/side_panel");var S=function(a,b,c=null){if(b==null)return b;var d=typeof b;if(d==="boolean"||d==="string"||d==="number")return b;if(d==="function")return"Function";if(d==="object"){let g=a.G.indexOf(b);if(g!==-1){a.cycles[c]=a.H[g];return}try{if(b&&typeof b[Symbol.iterator]==="function"){var f=[];a.G.push(b);a.H.push(c);var e=0;for(var k of b)f.push(S(a,k,c==null?`${e}`:`${c}.${e}`)),e++;return f}if(b instanceof Node){a=[];c=b;do{if(c instanceof Element){let H=c.classList?[...c.classList].join("."):"",I=(c.tagName?
c.tagName.toLowerCase():"")+(H?"."+H:"")+(c.id?"#"+c.id:"");I&&a.unshift(I)}c=c.parentNode}while(c!=null);var h;let l=(h=(e=b.toString().match(/\[object (\w+)\]/))==null?void 0:e[1])!=null?h:b.toString(),n=a.join(" > ");return n?`${l}: ${n}`:l}k={};a.G.push(b);a.H.push(c);for(let [l,n]of Object.entries(b))e=l,h=n,f=e.replace(/\\/g,"\\\\").replace(/\./,"\\."),k[e]=S(a,h,c==null?`${f}`:`${c}.${f}`);return k}catch(l){console.log("Object inspection failed: %o",l)}}try{return String(b)}catch(g){console.log("Failed to convert to string: %o",
g);try{return String(Object.prototype.toString.call(b))}catch(l){return`[${d}]`}}};class ja{constructor(){this.cycles={};this.G=[];this.H=[]}};var U=function(a){var b=a.g["google.tagmanager.ta.prodqueue"];if(b){T(a,[...b]);var c=b.push;b.push=(...d)=>{T(a,d);return c.apply(b,d)}}else Date.now()-a.S<1E4&&a.g.setTimeout(()=>{U(a)},300)},T=function(a,b){for(let c of b)c.messageType!=="INIT"||a.T.push(c),b=new ja,b={sanitized:S(b,c),cycles:b.cycles},a.i({type:"MEMO",data:{memo:b,sequence:a.L,pageId:a.pageId},uId:""}),a.L++},ka=class{constructor(a,b){this.g=a;this.i=b;this.S=Date.now();this.L=0;this.T=[];b=new Uint8Array(16);a.crypto.getRandomValues(b);
this.pageId=a.btoa(String.fromCharCode(...b)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");U(this)}};function V(a){if(a==null||a.length===0)return!1;a=Number(a);var b=(new Date(Date.now())).getTime();return a<b+3E5&&a>b-9E5};function W(a){return a.replace(/([\?&])gtm_debug=x&/,"$1").replace(/[\?&]gtm_debug=x($|#)/,"$1")};var la=function(a){var b=a.g.document.documentElement.getAttribute("data-tag-assistant-prod-present");if(V(b))a.startProdDebug();else{let c=d=>{d.detail.startProdDebug&&a.startProdDebug();a.g.document.removeEventListener("TADebugSignal",c)};a.g.document.addEventListener("TADebugSignal",c)}},ma=function(a){if(a.g.top===a.g){var b=a.g.document.documentElement.getAttribute("data-tag-assistant-present")||a.g.document.documentElement.getAttribute("data-tag-assistant-prod-present");if(V(b))M(a.A);else{let c=
d=>{d.detail.startDebug&&M(a.A);a.g.document.removeEventListener("TADebugSignal",c)};a.g.document.addEventListener("TADebugSignal",c)}}},na=function(a,b){a.F.push(b);a.N||(a.N=!0,a.g.document.addEventListener("prerenderingchange",()=>{for(let c of a.F)X(a,c);a.F.length=0},{once:!0}))},X=function(a,b){a.g.document.dispatchEvent(new CustomEvent("__TAG_ASSISTANT_API_MESSAGE",{detail:b}))},Y=function(a,b){if(b!=="RESEND_MEMOS"||a.g===a.g.top){b=a.i;var c=Object,d=c.assign,f=a.g,e;var k=W(f.location.href);
var h;if(!(h=f.document.title)&&(h=f.location.href,h!=="/")){try{var g=new URL(h);g.search="";g.hash="";h=g.toString()}catch(l){}g=h.split("/");h=g[g.length-1]||g[g.length-2]}k={href:k,title:h,referrer:W((e=f.document.referrer)!=null?e:""),readyState:f.document.readyState};e=a.g;e=e.google_tag_manager=e.google_tag_manager||{};e=e.debugGroupId||(e.debugGroupId=String(Math.floor(Number.MAX_SAFE_INTEGER*Math.random())));b.call(a,{type:"PAGE_SUMMARY",data:d.call(c,{},k,{groupId:e}),uId:""})}},oa=function(a){a.g===
a.g.top&&(a.C=a.g.setInterval(()=>{a.i({type:"PING",uId:""})},1E3),a.g.document.readyState==="complete"?Y(a):a.g.addEventListener("load",()=>{Y(a)}))},pa=class{constructor(a){this.g=Z;this.R=a;this.F=[];this.N=!1;this.A=new fa(this.g);this.g.document.addEventListener("__TAG_ASSISTANT_API_MESSAGE",b=>{b=b.detail;a:{var c=b==null?void 0:b.type;if(typeof c!=="string")c=!1;else switch(c){case "API_INSTALLED":case "CHECK_DEBUG":case "DISCONNECT":case "PIPE_MESSAGE":case "RECONNECT":case "WINDOWS_CLOSED":c=
!0;break a;default:c=!1}}if(c)a:if(c=b==null?void 0:b.source,typeof c!=="string")c=!1;else switch(c){case "PAGE":case "EXTENSION":c=!0;break a;default:c=!1}c&&b.type==="PIPE_MESSAGE"&&b.source==="EXTENSION"&&(c=b.data,b=b.origin,c.type!=="SIDE_PANEL"&&(c.type!=="RESEND_MEMOS"||this.receiver||Y(this,"RESEND_MEMOS"),oa(this),this.receiver&&this.receiver(c,b)))});this.g.document.dispatchEvent(new CustomEvent("__TAG_ASSISTANT_API_MESSAGE",{detail:{type:"API_INSTALLED",source:"PAGE"}}));this.g.addEventListener("pagehide",
()=>{this.J!=null&&(this.g.clearInterval(this.J),this.J=void 0)});la(this);ma(this);ea(this.A,b=>{b&&this.i({type:"CONNECTION_ISSUE",data:b,uId:""})})}setReceiver(a){this.receiver=a}sendMessage(a){this.C&&(this.g.clearInterval(this.C),this.C=void 0);this.i(a)}i(a){a={type:"PIPE_MESSAGE",source:"PAGE",data:a,origin:this.g.origin,dId:"",tId:0};this.g.document.prerendering?na(this,a):X(this,a)}disconnect(){this.g.document.dispatchEvent(new CustomEvent("__TAG_ASSISTANT_API_MESSAGE",{detail:{type:"DISCONNECT",
source:"PAGE"}}));this.R()}startProdDebug(){this.V=this.V||new ka(this.g,a=>{this.i(a)})}};var Z=window;Z.__TAG_ASSISTANT_API||(Z.__TAG_ASSISTANT_API=new pa(()=>{Z.__TAG_ASSISTANT_API=void 0}));}).call(this);
