from __future__ import annotations

from typing import Protocol

from src.shared.contracts.inventory import (
    InventorySyncBatchResult,
    InventorySyncRecord,
    ShopifyInventoryState,
    SupplierInventory,
)
from src.shared.contracts.listing import ListingBatchResult, ShopifyDraftProduct
from src.shared.contracts.mapping import SkuMappingRecord
from src.shared.contracts.pricing import (
    PlatformCost,
    PricingDecision,
    PriceSyncBatchResult,
    PriceSyncRecord,
    ShippingCost,
    ShopifyPriceState,
    SupplierCost,
    WarehouseCost,
)
from src.shared.contracts.risk import (
    ApprovalQueueItem,
    BlockedProduct,
    RiskAlert,
    RiskBatchResult,
    RiskEvent,
    RiskReport,
    RiskScore,
    SupplierRiskScore,
)
from src.shared.contracts.screening import (
    CandidatePoolBatchResult,
    ListingCandidate,
    ProductScore,
    ProductScoreBatchResult,
    RuleEngineResult,
    ScreeningDecision,
)
from src.shared.contracts.supplier_archive import (
    InventorySnapshot,
    PriceSnapshot,
    ProductSnapshot,
    ScreeningInput,
    SellerSnapshot,
    SupplierProduct,
)


class DecisionLogRepository(Protocol):
    def save(self, decision: ScreeningDecision) -> dict: ...


class SkuMappingRepository(Protocol):
    def get_by_sku(self, sku: str) -> SkuMappingRecord | None: ...
    def get_by_supplier_product_id(self, supplier_product_id: str) -> SkuMappingRecord | None: ...
    def save(self, record: SkuMappingRecord) -> SkuMappingRecord: ...
    def list_all(self) -> list[SkuMappingRecord]: ...


class ProductStateRepository(Protocol):
    def is_duplicate(self, duplicate_key: str) -> bool: ...
    def remember(self, duplicate_key: str) -> None: ...


class ListingRepository(Protocol):
    def mark_created(self, duplicate_key: str, draft_id: str) -> None: ...
    def get_draft_id(self, duplicate_key: str) -> str | None: ...
    def save_shopify_product(self, product: ShopifyDraftProduct) -> ShopifyDraftProduct: ...
    def list_shopify_products(self) -> list[ShopifyDraftProduct]: ...
    def get_shopify_product_by_supplier_sku(self, supplier_sku: str) -> ShopifyDraftProduct | None: ...
    def handle_exists(self, handle: str) -> bool: ...
    def product_hash_exists(self, product_hash: str) -> bool: ...
    def save_listing_batch_result(self, result: ListingBatchResult) -> ListingBatchResult: ...
    def list_listing_batch_results(self) -> list[ListingBatchResult]: ...


class SupplierArchiveRepository(Protocol):
    def save_supplier_product(self, product: SupplierProduct) -> SupplierProduct: ...
    def list_supplier_products(self) -> list[SupplierProduct]: ...
    def save_product_snapshot(self, snapshot: ProductSnapshot) -> ProductSnapshot: ...
    def list_product_snapshots(self) -> list[ProductSnapshot]: ...
    def save_inventory_snapshot(self, snapshot: InventorySnapshot) -> InventorySnapshot: ...
    def list_inventory_snapshots(self) -> list[InventorySnapshot]: ...
    def save_price_snapshot(self, snapshot: PriceSnapshot) -> PriceSnapshot: ...
    def list_price_snapshots(self) -> list[PriceSnapshot]: ...
    def save_seller_snapshot(self, snapshot: SellerSnapshot) -> SellerSnapshot: ...
    def list_seller_snapshots(self) -> list[SellerSnapshot]: ...
    def save_screening_input(self, screening_input: ScreeningInput) -> ScreeningInput: ...
    def list_screening_inputs(self) -> list[ScreeningInput]: ...


class ProductScreeningRepository(Protocol):
    def save_rule_engine_result(self, result: RuleEngineResult) -> RuleEngineResult: ...
    def list_rule_engine_results(self) -> list[RuleEngineResult]: ...
    def save_pre_filtered_product(self, product: ScreeningInput) -> ScreeningInput: ...
    def list_pre_filtered_products(self) -> list[ScreeningInput]: ...
    def save_ai_product_score(self, score: ProductScore) -> ProductScore: ...
    def list_ai_product_scores(self) -> list[ProductScore]: ...
    def get_latest_ai_product_score(self, supplier_sku: str) -> ProductScore | None: ...
    def save_product_score_batch_result(self, result: ProductScoreBatchResult) -> ProductScoreBatchResult: ...
    def save_listing_candidate(self, candidate: ListingCandidate) -> ListingCandidate: ...
    def list_listing_candidates(self) -> list[ListingCandidate]: ...
    def get_listing_candidate_by_sku(self, supplier_sku: str) -> ListingCandidate | None: ...
    def save_candidate_pool_batch_result(self, result: CandidatePoolBatchResult) -> CandidatePoolBatchResult: ...
    def list_candidate_pool_batch_results(self) -> list[CandidatePoolBatchResult]: ...


class SupplierInventoryRepository(Protocol):
    def save_supplier_inventory(self, inventory: SupplierInventory) -> SupplierInventory: ...
    def list_supplier_inventories(self) -> list[SupplierInventory]: ...
    def get_supplier_inventory_by_sku(self, supplier_sku: str) -> SupplierInventory | None: ...


class ShopifyInventoryRepository(Protocol):
    def save_shopify_inventory_state(self, state: ShopifyInventoryState) -> ShopifyInventoryState: ...
    def list_shopify_inventory_states(self) -> list[ShopifyInventoryState]: ...
    def get_shopify_inventory_state_by_sku(self, supplier_sku: str) -> ShopifyInventoryState | None: ...


class InventorySyncLogRepository(Protocol):
    def save_inventory_sync_record(self, record: InventorySyncRecord) -> InventorySyncRecord: ...
    def list_inventory_sync_records(self) -> list[InventorySyncRecord]: ...


class InventorySyncBatchRepository(Protocol):
    def save_inventory_sync_batch_result(self, result: InventorySyncBatchResult) -> InventorySyncBatchResult: ...
    def list_inventory_sync_batch_results(self) -> list[InventorySyncBatchResult]: ...


class SupplierCostRepository(Protocol):
    def save_supplier_cost(self, cost: SupplierCost) -> SupplierCost: ...
    def list_supplier_costs(self) -> list[SupplierCost]: ...
    def get_supplier_cost_by_sku(self, supplier_sku: str) -> SupplierCost | None: ...


class ShippingCostRepository(Protocol):
    def save_shipping_cost(self, cost: ShippingCost) -> ShippingCost: ...
    def list_shipping_costs(self) -> list[ShippingCost]: ...
    def get_shipping_cost_by_sku(self, supplier_sku: str) -> ShippingCost | None: ...


class WarehouseCostRepository(Protocol):
    def save_warehouse_cost(self, cost: WarehouseCost) -> WarehouseCost: ...
    def list_warehouse_costs(self) -> list[WarehouseCost]: ...
    def get_warehouse_cost_by_sku(self, supplier_sku: str) -> WarehouseCost | None: ...


class PlatformCostRepository(Protocol):
    def save_platform_cost(self, cost: PlatformCost) -> PlatformCost: ...
    def list_platform_costs(self) -> list[PlatformCost]: ...
    def get_platform_cost_by_sku(self, supplier_sku: str) -> PlatformCost | None: ...


class ShopifyPriceRepository(Protocol):
    def save_shopify_price_state(self, state: ShopifyPriceState) -> ShopifyPriceState: ...
    def list_shopify_price_states(self) -> list[ShopifyPriceState]: ...
    def get_shopify_price_state_by_sku(self, supplier_sku: str) -> ShopifyPriceState | None: ...


class PricingDecisionRepository(Protocol):
    def save_pricing_decision(self, decision: PricingDecision) -> PricingDecision: ...
    def list_pricing_decisions(self) -> list[PricingDecision]: ...


class PriceSyncLogRepository(Protocol):
    def save_price_sync_record(self, record: PriceSyncRecord) -> PriceSyncRecord: ...
    def list_price_sync_records(self) -> list[PriceSyncRecord]: ...


class PriceSyncBatchRepository(Protocol):
    def save_price_sync_batch_result(self, result: PriceSyncBatchResult) -> PriceSyncBatchResult: ...
    def list_price_sync_batch_results(self) -> list[PriceSyncBatchResult]: ...


class RiskEventRepository(Protocol):
    def save_risk_event(self, event: RiskEvent) -> RiskEvent: ...
    def list_risk_events(self) -> list[RiskEvent]: ...


class RiskAlertRepository(Protocol):
    def save_risk_alert(self, alert: RiskAlert) -> RiskAlert: ...
    def list_risk_alerts(self) -> list[RiskAlert]: ...


class RiskReportRepository(Protocol):
    def save_risk_report(self, report: RiskReport) -> RiskReport: ...
    def list_risk_reports(self) -> list[RiskReport]: ...


class ApprovalQueueRepository(Protocol):
    def save_approval_queue_item(self, item: ApprovalQueueItem) -> ApprovalQueueItem: ...
    def list_approval_queue_items(self) -> list[ApprovalQueueItem]: ...


class BlockedProductRepository(Protocol):
    def save_blocked_product(self, product: BlockedProduct) -> BlockedProduct: ...
    def list_blocked_products(self) -> list[BlockedProduct]: ...


class SupplierRiskRepository(Protocol):
    def save_supplier_risk_score(self, score: SupplierRiskScore) -> SupplierRiskScore: ...
    def list_supplier_risk_scores(self) -> list[SupplierRiskScore]: ...


class RiskScoreRepository(Protocol):
    def save_risk_score(self, score: RiskScore) -> RiskScore: ...
    def list_risk_scores(self) -> list[RiskScore]: ...


class RiskBatchRepository(Protocol):
    def save_risk_batch_result(self, result: RiskBatchResult) -> RiskBatchResult: ...
    def list_risk_batch_results(self) -> list[RiskBatchResult]: ...
