(function(){'use strict';var aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},n=ba(this),p=function(a,b){if(b)a:{var c=n;a=a.split(".");for(var d=
0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}},ca=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},da=function(a){this[Symbol.asyncIterator]=function(){return this};this[Symbol.iterator]=function(){return a};this.next=function(b){return Promise.resolve(a.next(b))};this["throw"]=function(b){return new Promise(function(c,d){var e=a["throw"];e!==void 0?c(e.call(a,
b)):(c=a["return"],c!==void 0&&c.call(a),d(new TypeError("no `throw` method")))})};a["return"]!==void 0&&(this["return"]=function(b){return Promise.resolve(a["return"](b))})};p("globalThis",function(a){return a||n});p("Promise.withResolvers",function(a){return a?a:function(){var b,c;return{promise:new Promise(function(d,e){b=d;c=e}),resolve:b,reject:c}}});function q(a){var b=a.passthroughEventType;if(!a.params)return`${b}`;a=r(a.params);return`${b}/${a}`}function u(a){var b=0;for(let c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b}function r(a){if(!a||Object.keys(a).length===0)return 0;var b=Object.keys(a).sort(),c=0;for(let e=0,g;g=b[e];e++){var d=a[g];if(!d)continue;c=31*c+u(g);c%=4294967296;d=typeof d==="object"?r(d):u(d.toString());c=31*c+d;c%=4294967296}return c};var w=class{constructor(){this.map=new Map}get(a){a=q(a);var b;return(b=this.map.get(a))==null?void 0:b.value}set(a,b){var c=q(a);this.map.set(c,{subscription:a,value:b})}has(a){a=q(a);return this.map.has(a)}delete(a){a=q(a);return this.map.delete(a)}clear(){this.map.clear()}get size(){return this.map.size}};var ea=1;async function x(a,{tabId:b,frameId:c,context:d,argument:e}={}){var g=a;g.passthroughApiRequestId||(g={passthroughApiRequestId:ea++,name:a,tabId:b,frameId:c,context:d,argument:e});a=await fa(g);if(a.error)throw a.error;return a.result}
async function fa(a){var b=Date.now(),c=a.tabId;if(!c){c=(await chrome.tabs.query({active:!0,currentWindow:!0}))[0];if(!c)throw Error("No active tab");if(!c.id)throw Error("Active tab has unknown ID");c=c.id}for(;;)try{let d;return await chrome.tabs.sendMessage(c,a,{frameId:(d=a.frameId)!=null?d:0})}catch(d){if(Date.now()-b>4900||d&&d.message!=="Could not establish connection. Receiving end does not exist.")throw d;await ia()}}function ia(){return new Promise(a=>{setTimeout(a,100)})};var z=function(a,b,c){return a.g(b,{tabId:a.reference.tabId,frameId:a.reference.frameId,context:a.reference,argument:c})},A=class{constructor(a,b,c,d){this.reference=a;this.g=b;this.subscribe=c;this.unsubscribe=d}async querySelector(a){return(a=await z(this,"element.querySelector",a))?this.wrap(a):void 0}async querySelectorAll(a){return(await z(this,"element.querySelectorAll",a)).map(b=>this.wrap(b))}async evaluate(a){a.includes("./")||a.includes("descendant")||a.includes("ancestor");return(await z(this,
"element.evaluate",a)).map(b=>this.wrap(b))}scrollIntoView(){return z(this,"element.scrollIntoView")}getAttribute(a){return z(this,"element.getAttribute",a)}click(){return z(this,"element.click")}remove(){try{return z(this,"element.remove")}catch(a){return Promise.resolve()}}wrap(a){return new A(a,this.g,this.subscribe,this.unsubscribe)}};/*


 Copyright (c) 2015-2018 Google, Inc., Netflix, Inc., Microsoft Corp. and contributors
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var B=class extends Error{constructor(a){super(a?`${a.length} errors occurred during unsubscription:
${a.map((b,c)=>`${c+1}) ${b.toString()}`).join("\n  ")}`:"");this.errors=a;Object.setPrototypeOf(this,new.target.prototype);this.name="UnsubscriptionError"}};function C(a,b){a&&(b=a.indexOf(b),0<=b&&a.splice(b,1))};function D(a){return typeof a==="function"};var E=class{constructor(a){this.V=a;this.closed=!1;this.m=this.i=null}unsubscribe(){if(!this.closed){this.closed=!0;let c=this.i;if(Array.isArray(c))for(var a of c)a.remove(this);else c==null||c.remove(this);a=this.V;if(D(a))try{a()}catch(e){var b=e instanceof B?e.errors:[e]}let d=this.m;if(d){this.m=null;for(let e of d)try{D(e)?e():e.unsubscribe()}catch(g){let f;b=(f=b)!=null?f:[];g instanceof B?b=[...b,...g.errors]:b.push(g)}}if(b)throw new B(b);}}add(a){if(a&&a!==this)if(this.closed)D(a)?a():a.unsubscribe();
else{if(a instanceof E){if(a.closed||a.N(this))return;a.J(this)}let b;(this.m=(b=this.m)!=null?b:[]).push(a)}}N(a){var b=this.i;return b===a||Array.isArray(b)&&b.includes(a)}J(a){var b=this.i;this.i=Array.isArray(b)?(b.push(a),b):b?[b,a]:a}R(a){var b=this.i;b===a?this.i=null:Array.isArray(b)&&C(b,a)}remove(a){var b=this.m;b&&C(b,a);a instanceof E&&a.R(this)}},ja=E,F=new E;F.closed=!0;ja.EMPTY=F;function ka(a){return a instanceof E||a&&"closed"in a&&D(a.remove)&&D(a.add)&&D(a.unsubscribe)};function G(a){setTimeout(()=>{throw a;})};var ma=class extends E{static create(a,b,c){return new H(a,b,c)}constructor(){super();this.h=!1;this.destination=new la({next:void 0});ka()&&(void 0).add(this)}next(a){this.h||this.P(a)}error(a){this.h||(this.h=!0,this.M(a))}complete(){this.h||(this.h=!0,this.L())}unsubscribe(){this.closed||(this.h=!0,super.unsubscribe())}P(a){this.destination.next(a)}M(a){this.destination.error(a);this.unsubscribe()}L(){this.destination.complete();this.unsubscribe()}};
class la{constructor(a){this.G=a}next(a){var b=this.G;if(b.next)try{b.next(a)}catch(c){G(c)}}error(a){var b=this.G;if(b.error)try{b.error(a)}catch(c){G(c)}else G(a)}complete(){var a=this.G;if(a.complete)try{a.complete()}catch(b){G(b)}}}var H=class extends ma{constructor(a,b,c){super();this.destination=new la(D(a)||!a?{next:a!=null?a:void 0,error:b!=null?b:void 0,complete:c!=null?c:void 0}:a)}};var I=typeof Symbol==="function"&&Symbol.observable||"@@observable";function na(a){return a};function oa(a){return a.length===0?na:a.length===1?a[0]:function(b){return a.reduce((c,d)=>d(c),b)}};var pa=function(a,...b){return b.length?oa(b)(a):a},J=class{constructor(a){a&&(this.l=a)}D(a){var b=new J;b.source=this;b.operator=a;return b}subscribe(a,b,c){a=a&&a instanceof ma||a&&D(a.next)&&D(a.error)&&D(a.complete)&&ka(a)?a:new H(a,b,c);b=this.operator;c=this.source;a.add(b?b.call(a,c):c?this.l(a):this.v(a));return a}v(a){try{return this.l(a)}catch(b){a.error(b)}}forEach(a,b){b=qa(b);return new b((c,d)=>{var e=this.subscribe(g=>{try{a(g)}catch(f){d(f),e==null||e.unsubscribe()}},d,c)})}l(a){var b;
return(b=this.source)==null?void 0:b.subscribe(a)}[I](){return this}};J.create=a=>new J(a);function qa(a){var b;return(b=a!=null?a:void 0)!=null?b:Promise};var ra=class extends Error{constructor(){super("object unsubscribed");Object.setPrototypeOf(this,new.target.prototype);this.name="ObjectUnsubscribedError"}};var K=class extends J{constructor(){super();this.j=[];this.B=this.h=this.closed=!1;this.I=null}D(a){var b=new sa(this,this);b.operator=a;return b}o(){if(this.closed)throw new ra;}next(a){this.o();if(!this.h){let b=this.j.slice();for(let c of b)c.next(a)}}error(a){this.o();if(!this.h){this.B=this.h=!0;this.I=a;let b=this.j;for(;b.length;)b.shift().error(a)}}complete(){this.o();if(!this.h){this.h=!0;let a=this.j;for(;a.length;)a.shift().complete()}}unsubscribe(){this.h=this.closed=!0;this.j=null}v(a){this.o();
return super.v(a)}l(a){this.o();this.K(a);return this.O(a)}O(a){var b=this.h,c=this.j;return this.B||b?E.EMPTY:(c.push(a),new E(()=>C(this.j,a)))}K(a){var b=this.I,c=this.h;this.B?a.error(b):c&&a.complete()}};K.create=(a,b)=>new sa(a,b);
var sa=class extends K{constructor(a,b){super();this.destination=a;this.source=b}next(a){var b,c;(b=this.destination)==null||(c=b.next)==null||c.call(b,a)}error(a){var b,c;(b=this.destination)==null||(c=b.error)==null||c.call(b,a)}complete(){var a,b;(a=this.destination)==null||(b=a.complete)==null||b.call(a)}l(a){var b,c;return(c=(b=this.source)==null?void 0:b.subscribe(a))!=null?c:E.EMPTY}};var ta=typeof Symbol==="function"&&Symbol.iterator?Symbol.iterator:"@@iterator";function ua(a){if(a instanceof J)return a;if(a!=null){if(D(a[I]))return va(a);if(a&&typeof a.length==="number"&&typeof a!=="function")return wa(a);if(D(a==null?void 0:a.then))return xa(a);if(Symbol.asyncIterator&&D(a==null?void 0:a[Symbol.asyncIterator]))return ya(a);if(D(a==null?void 0:a[ta]))return za(a)}throw new TypeError(`You provided ${a!==null&&typeof a==="object"?"an invalid object":`'${a}'`} where a stream was expected. You can provide an Observable, Promise, Array, AsyncIterable, or Iterable.`);
}function va(a){return new J(b=>{var c=a[I]();if(D(c.subscribe))return c.subscribe(b);throw new TypeError("Provided object does not correctly implement Symbol.observable");})}function wa(a){return new J(b=>{for(let c=0;c<a.length&&!b.closed;c++)b.next(a[c]);b.complete()})}function xa(a){return new J(b=>{a.then(c=>{b.closed||(b.next(c),b.complete())},c=>b.error(c)).then(null,G)})}
function za(a){return new J(b=>{for(var c=a[ta]();!b.closed;){let {done:d,value:e}=c.next();d?b.complete():b.next(e)}return()=>D(c==null?void 0:c.return)&&c.return()})}function ya(a){return new J(b=>{Aa(a,b).catch(c=>b.error(c))})}
async function Aa(a,b){var c;try{var d=a[Symbol.asyncIterator];if(d!==void 0)var e=d.call(a);else{var g=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(g)var f=g.call(a);else if(typeof a.length=="number")f={next:ca(a)};else throw Error(String(a)+" is not an iterable or ArrayLike");e=new da(f)}for(var h=e;;){var k=await h.next();if(k.done)break;b.next(k.value)}}catch(l){var m={error:l}}finally{try{k&&!k.done&&(c=h.return)&&await c.call(h)}finally{if(m)throw m.error;}}b.complete()}
;function Ba(a){return b=>{if(D(b==null?void 0:b.D))return b.D(function(c){try{return a(c,this)}catch(d){this.error(d)}});throw new TypeError("Unable to lift unknown Observable type");}};function Ca(a){return Ba((b,c)=>{b.subscribe(c);c.add(a)})};function Da(){var a=a||{};var {da:b=()=>new K,fa:c=!0,ga:d=!0,ha:e=!0}=a;return g=>{var f=null,h=null,k=0,m=!1,l=!1;return Ba((v,y)=>{k++;var ha;h=(ha=h)!=null?ha:b();y.add(()=>{k--;if(e&&!k&&!l&&!m){let t=f;f=h=null;m=l=!1;t==null||t.unsubscribe()}});h.subscribe(y);!f&&k>0&&(f=new H({next:t=>h.next(t),error:t=>{l=!0;var Ka=h;d&&(f=h=null,m=l=!1);Ka.error(t)},complete:()=>{m=!0;var t=h;c&&(f=h=null,m=l=!1);t.complete()}}),ua(v).subscribe(f))})(g)}};var L=function(a,b){return new A(b,a.g,(c,d)=>a.subscribe(c,d),(c,d)=>{a.unsubscribe(c,d)})},Fa=class{constructor(){this.u=new w}async insertCSS(a,{tabId:b,frameId:c}={}){return this.g("insertCSS",{tabId:b,frameId:c,argument:a})}async evaluate(a,{tabId:b,frameId:c}={}){return(a=await this.g("evaluate",{tabId:b,frameId:c,argument:a}))?a.map(d=>L(this,d)):[]}async querySelector(a,{tabId:b,frameId:c}={}){return(a=await this.g("querySelector",{tabId:b,frameId:c,argument:a}))?L(this,a):void 0}async querySelectorAll(a,
{tabId:b,frameId:c}={}){return(await this.g("querySelectorAll",{tabId:b,frameId:c,argument:a})).map(d=>L(this,d))}async removeCSS(a,{tabId:b,frameId:c}={}){return this.g("removeCSS",{tabId:b,frameId:c,argument:a})}subscribe(a,b){var c={passthroughEventType:a,params:b},d=this.u.get(c);if(!d){switch(a){case "onMutationObserver":this.g("setMutationObserver",{tabId:b.tabId,frameId:b.frameId,argument:b});break;case "userDataDetected":setTimeout(()=>{this.g("startUserDataDetection",{tabId:b.tabId,frameId:b.frameId,
argument:b})},100);break;case "onDomClickEventDetected":setTimeout(()=>{this.g("startDomClickEventDetection",{tabId:b.tabId,frameId:b.frameId,argument:b})},100)}let e=new K;d={originalSubject:e,sharedObservable:pa(e,Ca(()=>{this.unsubscribe(a,b)}),Da())};this.u.set(c,d);Ea(c,e)}return d.sharedObservable}unsubscribe(a,b){var c={passthroughEventType:a,params:b};switch(a){case "onMutationObserver":this.g("clearMutationObserver",{tabId:b.tabId,frameId:b.frameId,argument:b});break;case "onMemoMessage":this.g("dispatchSidePanelMessage",
{argument:{tabId:b.tabId,type:"end_prod_debug_api"}});break;case "userDataDetected":this.g("stopUserDataDetection",{tabId:b.tabId,frameId:b.frameId,argument:b});break;case "onDomClickEventDetected":this.g("stopDomClickEventDetection",{tabId:b.tabId,frameId:b.frameId,argument:b});break;case "onDomEvent":break;default:this.g("unsubscribeFromEvent",{argument:c})}this.u.has(c)&&this.u.delete(c)}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var Ga=globalThis.trustedTypes,M;function Ha(){var a=null;if(!Ga)return a;try{let b=c=>c;a=Ga.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var N=class{constructor(a){this.H=a}toString(){return this.H+""}};function O(a){var b;M===void 0&&(M=Ha());a=(b=M)?b.createScriptURL(a):a;return new N(a)}function P(a){if(a instanceof N)return a.H;throw Error("");};function Q(a,...b){if(b.length===0)return O(a[0]);var c=a[0];for(let d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return O(c)}function Ia(a,b,c,d){function e(f,h){f!=null&&(Array.isArray(f)?f.forEach(k=>e(k,h)):(b+=g+encodeURIComponent(h)+"="+encodeURIComponent(f),g="&"))}var g=b.length?"&":"?";d.constructor===Object&&(d=Object.entries(d));Array.isArray(d)?d.forEach(f=>e(f[1],f[0])):d.forEach(e);return O(a+b+c)}var Ja=/[^#]*/;function R(a){return a.endsWith("/")?a.slice(0,-1):a}Q`cs/ta/tag_assistant_api_bin.js`;Q`cs/ta/content_script_bin.js`;Q`cs/ta/start_debug_content_script_bin.js`;Q`cs/ta/start_prod_debug_content_script_bin.js`;Q`cs/gf/guided_flows_content_script_bin.js`;R("https://tagassistant.google.com/guided_flows/open");R("https://tagassistant.google.com");var La=R("https://tagassistant.google.com/embedded/side_panel");function S(a,b=`unexpected value ${a}!`){throw Error(b);};var Ea=function(a,b){switch(a.passthroughEventType){case "domContentLoaded":chrome.webNavigation.onDOMContentLoaded.addListener(c=>{b.next(c)});break;case "tabActivated":chrome.tabs.onActivated.addListener(c=>{b.next(c)});break;case "tabCreated":throw Error("Tab created subscription not supported.");case "tabUpdated":chrome.tabs.onUpdated.addListener((c,d,e)=>{b.next({tabId:c,changeInfo:d,tab:e})});break;case "webNavigationCommitted":chrome.webNavigation.onCommitted.addListener(c=>{b.next(c)});break;
case "webNavigationCompleted":chrome.webNavigation.onCompleted.addListener(c=>{b.next(c)});break;case "onMutationObserver":break;case "onDomEvent":break;case "onMemoMessage":break;case "onDomClickEventDetected":break;default:S(a.passthroughEventType,"type had an unknown type")}},Ma=async function(){return chrome.runtime.id},Na=function(a,b){return a!==void 0&&b!==void 0?chrome.tabs.reload(a,b):a!==void 0?chrome.tabs.reload(a):b?chrome.tabs.reload(b):chrome.tabs.reload()},Oa=class extends Fa{constructor(){super(...arguments);
this.g=x}getAllFrames(a){return chrome.webNavigation.getAllFrames(a)}getManifest(){return Promise.resolve(chrome.runtime.getManifest())}navigate(a,b){return new Promise((c,d)=>{var e,g=setTimeout(()=>void d(Error("Timed out waiting for page to load")),(e=b==null?void 0:b.timeoutMs)!=null?e:3E4);chrome.tabs.update(b.tabId,{url:a},f=>void chrome.tabs.onUpdated.addListener(function l(k,m){k===(f==null?void 0:f.id)&&m.status==="complete"&&(clearTimeout(g),chrome.tabs.onUpdated.removeListener(l),c())}))})}};var Pa=Promise;class Qa{constructor(a){this.S=a}send(a,b,c){this.S.then(d=>{d.send(a,b,c)})}};class Ra{constructor(a,b){this.data=a;this.channel=b}};var Ua=function(a,b){Sa(a,b);return new Ta(a)};class Ta{constructor(a){this.Y=a}send(a,b,c=[]){var d=new MessageChannel;Sa(d.port1,b);this.Y.postMessage(a,[d.port2].concat(c))}}var Sa=function(a,b){b&&(a.onmessage=c=>{b(new Ra(c.data,Ua(c.ports[0])))})};var T=class{constructor(a){this.Z=a}verify(a){return this.Z(a)}},Va=a=>{var b=Object.create(null);(typeof a==="string"?[a]:a).forEach(c=>{if(c==="null")throw Error("Receiving from null origin not allowed without token verification. Please use NullOriginConnector.");b[c]=!0});return c=>b[c]===!0};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Xa=({destination:a,U:b,origin:c,A:d="ZNWN1d",onMessage:e,F:g})=>Wa({destination:a,T:()=>b.contentWindow,X:c instanceof T?c:typeof c==="function"?new T(c):new T(Va(c)),A:d,onMessage:e,F:g}),Wa=({destination:a,T:b,X:c,token:d,A:e,onMessage:g,F:f})=>new Qa(new Pa((h,k)=>{var m=l=>{l.source&&l.source===b()&&c.verify(l.origin)&&(l.data.n||l.data)===e&&(a.removeEventListener("message",m,!1),d&&l.data.t!==d?k(Error(`Token mismatch while establishing channel "${e}". Expected ${d}, but received ${l.data.t}.`)):
(h(Ua(l.ports[0],g)),f&&f(l)))};a.addEventListener("message",m,!1)}));var Ya,U,V=new w;function Za(a){var b=Xa({destination:window,U:a,origin:(new URL(a.src)).origin,A:"passthrough_api",onMessage:c=>{$a(c);ab(c)},F:()=>{Ya=b;Za(a)}})}
async function $a(a){var b=a.data;if(b.passthroughApiRequestId){var c=async e=>void bb(a,{result:await e}),d=new Oa;try{switch(b.name){case "createTab":await c(Promise.resolve(chrome.tabs.create(b.argument)));break;case "createWindow":await c(Promise.resolve(chrome.windows.create(b.argument)));break;case "getAllFrames":await c(d.getAllFrames(b.argument));break;case "getExtensionId":await c(Ma());break;case "dispatchSidePanelMessage":let e=b.argument;await c(chrome.runtime.sendMessage({tabId:e.tabId,
type:e.type}));break;case "getLocalStorage":await c(chrome.storage.local.get(b.argument));break;case "getManifest":await c(d.getManifest());break;case "getTab":await c(Promise.resolve(chrome.tabs.get(b.argument)));break;case "insertCSS":await c(cb(b));break;case "navigate":if(typeof b.argument==="string")await c(d.navigate(b.argument,{tabId:W(),timeoutMs:3E4}));else{let k=b.argument.timeoutMs,m;await c(d.navigate(b.argument.url,{tabId:(m=b.argument.tabId)!=null?m:W(),timeoutMs:k!=null?k:3E4}))}break;
case "queryTab":await c(chrome.tabs.query(b.argument));break;case "reloadTab":let g=b.argument;await c(Na(g.tabId,g.reloadProperties));break;case "updateTab":await c(chrome.tabs.update(b.argument.tabId,b.argument.updateProperties));break;case "removeCSS":await c(db(b));break;case "removeTab":await chrome.tabs.remove(b.argument);break;case "setIframeTitle":U.title=b.argument;await c();break;case "setLocalStorage":await c(chrome.storage.local.set(b.argument));break;case "unsubscribeFromEvent":let f=
b.argument,h=V.get(f);h&&(h(),V.delete(f));await c();break;case "element.getCodeMirrorValue":await x("element.markDomForReference",{context:b.context});await c(eb(b));break;case "element.setCodeMirrorValue":await x("element.markDomForReference",{context:b.context});await c(fb(b));break;case "element.selectCodeMirrorText":await x("element.markDomForReference",{context:b.context,tabId:b.tabId,frameId:b.frameId});await c(gb(b));break;case "clearMutationObserver":case "evaluate":case "getAllHtmlComments":case "hasHtmlComment":case "querySelector":case "querySelectorAll":case "setMutationObserver":case "element.addEventListener":case "element.dispatchCustomEvent":case "element.dispatchMouseEvent":case "element.applyStyles":case "element.click":case "element.evaluate":case "element.getAttribute":case "element.getInputValue":case "element.getTextContent":case "element.insertComponent":case "element.markDomForReference":case "element.querySelector":case "element.querySelectorAll":case "element.remove":case "element.setInputValue":case "element.scrollIntoView":case "startUserDataDetection":case "stopUserDataDetection":case "startDomClickEventDetection":case "stopDomClickEventDetection":await c(x(b));
break;default:S(b.name,"Unknown request")}}catch(e){bb(a,{error:e})}}}async function eb(a){var b=a.context.id,c,d;return(d=(c=(await chrome.scripting.executeScript({target:X(a),world:"MAIN",args:[Y(b)],func:e=>{var g,f,h;return(h=(g=document.querySelector(e))==null?void 0:(f=g.CodeMirror)==null?void 0:f.getValue())!=null?h:""}}))[0])==null?void 0:c.result)!=null?d:""}
async function fb(a){var b=a.context.id,c=a.argument;return chrome.scripting.executeScript({target:X(a),world:"MAIN",args:[Y(b),c],func:(d,e)=>{(d=document.querySelector(d))&&d.CodeMirror&&d.CodeMirror.setValue(e)}})}
async function gb(a){var b=a.context.id,c=a.argument instanceof RegExp,d=c?a.argument.toString():a.argument,e,g;return(g=(e=(await chrome.scripting.executeScript({target:X(a),world:"MAIN",args:[Y(b),d,c],func:(f,h,k)=>{f=document.querySelector(f);if(!f)return!1;var m=k?new RegExp(h.slice(1,-1)):h;if(f.cmView){var l,v=(l=f.cmView.view.state.doc.toString().match(m))==null?void 0:l.index;if(v==null||v<0)return!1;f.cmView.view.dispatch({selection:{anchor:v}});return!0}if(f.CodeMirror){h=f.CodeMirror.getValue().split("\n");
l=h.findIndex(y=>y==null?void 0:y.match(m));h=(v=h[l])==null?void 0:v.match(m);if(l<0||!h)return!1;f.CodeMirror.setSelection({line:l,ch:h.index},{line:l,ch:h.index+h[0].length});return!0}return!1}}))[0])==null?void 0:e.result)!=null?g:!1}function cb(a){var b=a.argument;return chrome.scripting.insertCSS({target:X(a),css:b})}function db(a){var b=a.argument;return chrome.scripting.removeCSS({target:X(a),css:b})}
function X(a){var b,c;return{tabId:(b=a.tabId)!=null?b:W(),frameIds:[(c=a.frameId)!=null?c:0]}}
function ab(a){var b=a.data;if(b.passthroughEventType){var c=b.passthroughEventType;switch(c){case "domContentLoaded":chrome.webNavigation.onDOMContentLoaded.addListener(e=>{Z(a,b,e)});break;case "tabActivated":chrome.tabs.onActivated.addListener(e=>{Z(a,b,e)});break;case "tabUpdated":chrome.tabs.onUpdated.addListener((e,g,f)=>{Z(a,b,{tabId:e,changeInfo:g,tab:f})});break;case "tabCreated":if(V.has(b))break;let d=e=>{Z(a,b,e)};chrome.tabs.onCreated.addListener(d);V.set(b,()=>{chrome.tabs.onCreated.removeListener(d)});
break;case "webNavigationCommitted":chrome.webNavigation.onCommitted.addListener(e=>{Z(a,b,e)});break;case "webNavigationCompleted":chrome.webNavigation.onCompleted.addListener(e=>{Z(a,b,e)});break;case "onMutationObserver":chrome.runtime.onMessage.addListener((e,g)=>{if(g.tab)switch(e.type){case "onMutationObserver":e.data&&Z(a,b,e.data)}});break;case "onDomEvent":chrome.runtime.onMessage.addListener(e=>{e.type==="onDomEvent"&&e.data&&Z(a,b,e.data)});break;case "onMemoMessage":chrome.runtime.onMessage.addListener(e=>
{e.type==="onMemoMessage"&&e.data&&Z(a,b,e.data)});break;case "onDomClickEventDetected":chrome.runtime.onMessage.addListener(e=>{e.type==="onDomClickEventDetected"&&e.data&&Z(a,b,e.data)});break;default:S(c,"Unknown event")}}}function W(){var a=new URL(U.src),b,c=(b=a.searchParams.get("tabId"))!=null?b:a.searchParams.get("tab_id");return Number(c)}function Y(a){return`[data-${"tagAssistantReferenceId".replace(/([a-zA-Z])(?=[A-Z])/g,"$1-").toLowerCase()}="${a}"]`}
function bb(a,b){b=Object.assign({},b,{passthroughApiRequestId:a.data.passthroughApiRequestId});a.channel.send(b,void 0,void 0)}function Z(a,b,c){a.channel.send({subscription:b,data:c},void 0,void 0)};async function hb(a){try{let b=await a.i18n.getUILanguage();if(b)return b}catch(b){}}function ib(a){if(!a)return!1;try{switch(JSON.parse(atob(a)).purpose){case "guided_flows_install_ta":case "guided_flow_ads_conversion_setup":return!0;default:return!1}}catch(b){return!1}};var jb={ca:0,aa:1,ba:2,0:"FORMATTED_HTML_CONTENT",1:"EMBEDDED_INTERNAL_CONTENT",2:"EMBEDDED_TRUSTED_EXTERNAL_CONTENT"},kb=class extends Error{constructor(a){super(`${a} cannot be used with intent ${jb[1]}`);this.type=a;this.intent=1;this.name="TypeCannotBeUsedWithIframeIntentError"}};var mb=async function(){await (new lb).init()},nb=async function(a){var b=a.document.querySelector("iframe");if(b){var c=new URLSearchParams(a.window.location.search);var d=Number(c.get("tabId"));var e=c.get("url");var g=c.get("isWebdriverTest");var f=c.get("authuser");var h=c.get("flowType");var k=c.get("isPostLogin");c=c.get("context");d=isNaN(d)?void 0:{tabId:d,url:e,ea:g,authuser:f,flowType:h,W:k,context:c};if(d&&(g=O(La))){e=encodeURIComponent(a.C.runtime.getManifest().version);e=new Map([["origin",
a.window.origin],["utm_source","side_panel"],["tabId",`${d.tabId}`],["ext_version",`${e}`]]);d.authuser&&e.set("authuser",d.authuser);d.flowType&&e.set("flowType",d.flowType);d.W==="true"&&e.set("isPostLogin","true");d.context&&e.set("context",d.context);(f=await hb(a.C))&&e.set("hl",f);h=P(g).toString();k=h.split(/[?#]/);c=/[?]/.test(h)?"?"+k[1]:"";g=k[0];f=c;h=/[#]/.test(h)?"#"+(c?k[2]:k[1]):"";g=Ia(g,f,h,e);d.url?(e=`url=${d.url}`,g=P(g).toString(),e=O(Ja.exec(g)[0]+(e.trim()?"#"+e:""))):e=g;b.removeAttribute("srcdoc");
if(!(e instanceof N))throw new kb(typeof e);g="allow-same-origin allow-scripts allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation".split(" ");b.setAttribute("sandbox","");for(f=0;f<g.length;f++)b.sandbox.supports&&!b.sandbox.supports(g[f])||b.sandbox.add(g[f]);b.src=P(e).toString();ib(d.context)&&(a.C.runtime.connect({name:"sidePanel"}),Ya||(U=b,Za(b)))}}},lb=class{constructor(){var a=window,b=chrome;this.document=document;this.window=a;this.C=b}async init(){var a=
Promise.withResolvers();this.document.addEventListener("DOMContentLoaded",()=>{a.resolve(!0)});await a.promise&&nb(this)}};(async()=>{await mb()})();}).call(this);
