(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var m;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function q(a){if(!(a instanceof Array)){a=p(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);function r(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function da(){}da.prototype.toJSON=function(){return{}};function u(a){a.__shady||(a.__shady=new da);return a.__shady}function v(a){return a&&a.__shady};var w=window.ShadyDOM||{};w.oc=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ea=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");w.j=!!(ea&&ea.configurable&&ea.get);w.inUse=w.force||!w.oc;w.noPatch=w.noPatch||!1;w.X=w.preferPerformance;w.Da=w.noPatch==="on-demand";var fa;var ha=w.querySelectorImplementation;fa=["native","selectorEngine"].indexOf(ha)>-1?ha:void 0;w.querySelectorImplementation=fa;var ia=navigator.userAgent.match("Trident");w.jb=ia;
function ja(){return Document.prototype.msElementsFromPoint?"msElementsFromPoint":"elementsFromPoint"}function x(a){return(a=v(a))&&a.firstChild!==void 0}function y(a){return a instanceof ShadowRoot}function ka(a){return(a=(a=v(a))&&a.root)&&a.Na()}var z=Element.prototype,la=z.matches||z.matchesSelector||z.mozMatchesSelector||z.msMatchesSelector||z.oMatchesSelector||z.webkitMatchesSelector,ma=document.createTextNode(""),na=0,oa=[];
(new MutationObserver(function(){for(;oa.length;)try{oa.shift()()}catch(a){throw ma.textContent=na++,a;}})).observe(ma,{characterData:!0});function pa(a){oa.push(a);ma.textContent=na++}var ra=document.contains?function(a,b){return a.__shady_native_contains(b)}:function(a,b){return a===b||a.documentElement&&a.documentElement.__shady_native_contains(b)};function sa(a,b){for(;b;){if(b==a)return!0;b=b.__shady_parentNode}return!1}
function ta(a){for(var b=a.length-1;b>=0;b--){var c=a[b],e=c.getAttribute("id")||c.getAttribute("name");e&&e!=="length"&&isNaN(e)&&(a[e]=c)}a.item=function(d){return a[d]};a.namedItem=function(d){if(d!=="length"&&isNaN(d)&&a[d])return a[d];for(var f=p(a),g=f.next();!g.done;g=f.next())if(g=g.value,(g.getAttribute("id")||g.getAttribute("name"))==d)return g;return null};return a}function ua(a){var b=[];for(a=a.__shady_native_firstChild;a;a=a.__shady_native_nextSibling)b.push(a);return b}
function va(a){var b=[];for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)b.push(a);return b}function wa(a,b,c){c.configurable=!0;if(c.value)a[b]=c.value;else try{Object.defineProperty(a,b,c)}catch(e){}}function A(a,b,c,e){c=c===void 0?"":c;for(var d in b)e&&e.indexOf(d)>=0||wa(a,c+d,b[d])}function xa(a,b){for(var c in b)c in a&&wa(a,c,b[c])}function B(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=Object.getOwnPropertyDescriptor(a,c)});return b}
function ya(a,b){for(var c=Object.getOwnPropertyNames(b),e=0,d;e<c.length;e++)d=c[e],a[d]=b[d]}function za(a){return a instanceof Node?a:document.createTextNode(""+a)}function D(){var a=r.apply(0,arguments);if(a.length===1)return za(a[0]);var b=document.createDocumentFragment();a=p(a);for(var c=a.next();!c.done;c=a.next())b.appendChild(za(c.value));return b}
function Aa(a){var b;for(b=b===void 0?1:b;b>0;b--)a=a.reduce(function(c,e){Array.isArray(e)?c.push.apply(c,q(e)):c.push(e);return c},[]);return a}function Ba(a){var b=[],c=new Set;a=p(a);for(var e=a.next();!e.done;e=a.next())e=e.value,c.has(e)||(b.push(e),c.add(e));return b};var Ca=[],Da;function Ea(a){Da||(Da=!0,pa(Fa));Ca.push(a)}function Fa(){Da=!1;for(var a=!!Ca.length;Ca.length;)Ca.shift()();return a}Fa.list=Ca;function Ga(){this.ha=!1;this.addedNodes=[];this.removedNodes=[];this.ma=new Set}function Ha(a){a.ha||(a.ha=!0,pa(function(){a.flush()}))}Ga.prototype.flush=function(){if(this.ha){this.ha=!1;var a=this.takeRecords();a.length&&this.ma.forEach(function(b){b(a)})}};Ga.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Ia(a,b){var c=u(a);c.W||(c.W=new Ga);c.W.ma.add(b);var e=c.W;return{qb:b,M:e,Ob:a,takeRecords:function(){return e.takeRecords()}}}function Ja(a){var b=a&&a.M;b&&(b.ma.delete(a.qb),b.ma.size||(u(a.Ob).W=null))}
function Ka(a,b){var c=b.getRootNode();return a.map(function(e){var d=c===e.target.getRootNode();if(d&&e.addedNodes){if(d=[].slice.call(e.addedNodes).filter(function(f){return c===f.getRootNode()}),d.length)return e=Object.create(e),Object.defineProperty(e,"addedNodes",{value:d,configurable:!0}),e}else if(d)return e}).filter(function(e){return e})};var La=/[&\u00A0"]/g,Ma=/[&\u00A0<>]/g;function Na(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Oa(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Pa=Oa("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Qa=Oa("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function Ra(a,b){a.localName==="template"&&(a=a.content);for(var c="",e=b?b(a):a.childNodes,d=0,f=e.length,g=void 0;d<f&&(g=e[d]);d++){a:{var h=g;var k=a,l=b;switch(h.nodeType){case Node.ELEMENT_NODE:k=h.localName;for(var n="<"+k,t=h.attributes,C=0,qa;qa=t[C];C++)n+=" "+qa.name+'="'+qa.value.replace(La,Na)+'"';n+=">";h=Pa[k]?n:n+Ra(h,l)+"</"+k+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&Qa[k.localName]?h:h.replace(Ma,Na);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}h=void 0}c+=h}return c};var Sa=w.j,Ta={querySelector:function(a){return this.__shady_native_querySelector(a)},querySelectorAll:function(a){return this.__shady_native_querySelectorAll(a)}},Ua={};function Va(a){Ua[a]=function(b){return b["__shady_native_"+a]}}function Wa(a,b){A(a,b,"__shady_native_");for(var c in b)Va(c)}function E(a,b){b=b===void 0?[]:b;for(var c=0;c<b.length;c++){var e=b[c],d=Object.getOwnPropertyDescriptor(a,e);d&&(Object.defineProperty(a,"__shady_native_"+e,d),d.value?Ta[e]||(Ta[e]=d.value):Va(e))}}
var F=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),G=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),Xa=document.implementation.createHTMLDocument("inert");function Ya(a){for(var b;b=a.__shady_native_firstChild;)a.__shady_native_removeChild(b)}var Za=["firstElementChild","lastElementChild","children","childElementCount"],$a=["querySelector","querySelectorAll","append","prepend","replaceChildren"];
function ab(){var a=["dispatchEvent","addEventListener","removeEventListener"];window.EventTarget?(E(window.EventTarget.prototype,a),window.__shady_native_addEventListener===void 0&&E(Window.prototype,a)):(E(Node.prototype,a),E(Window.prototype,a),E(XMLHttpRequest.prototype,a));Sa?E(Node.prototype,"parentNode firstChild lastChild previousSibling nextSibling childNodes parentElement textContent".split(" ")):Wa(Node.prototype,{parentNode:{get:function(){F.currentNode=this;return F.parentNode()}},firstChild:{get:function(){F.currentNode=
this;return F.firstChild()}},lastChild:{get:function(){F.currentNode=this;return F.lastChild()}},previousSibling:{get:function(){F.currentNode=this;return F.previousSibling()}},nextSibling:{get:function(){F.currentNode=this;return F.nextSibling()}},childNodes:{get:function(){var b=[];F.currentNode=this;for(var c=F.firstChild();c;)b.push(c),c=F.nextSibling();return b}},parentElement:{get:function(){G.currentNode=this;return G.parentNode()}},textContent:{get:function(){switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(var b=
document.createTreeWalker(this,NodeFilter.SHOW_TEXT,null,!1),c="",e;e=b.nextNode();)c+=e.nodeValue;return c;default:return this.nodeValue}},set:function(b){if(typeof b==="undefined"||b===null)b="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:Ya(this);(b.length>0||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_native_insertBefore(document.createTextNode(b),void 0);break;default:this.nodeValue=b}}}});E(Node.prototype,"appendChild insertBefore removeChild replaceChild cloneNode contains".split(" "));
E(HTMLElement.prototype,["parentElement","contains"]);a={firstElementChild:{get:function(){G.currentNode=this;return G.firstChild()}},lastElementChild:{get:function(){G.currentNode=this;return G.lastChild()}},children:{get:function(){var b=[];G.currentNode=this;for(var c=G.firstChild();c;)b.push(c),c=G.nextSibling();return ta(b)}},childElementCount:{get:function(){return this.children?this.children.length:0}}};Sa?(E(Element.prototype,Za),E(Element.prototype,["previousElementSibling","nextElementSibling",
"innerHTML","className"]),E(HTMLElement.prototype,["children","innerHTML","className"])):(Wa(Element.prototype,a),Wa(Element.prototype,{previousElementSibling:{get:function(){G.currentNode=this;return G.previousSibling()}},nextElementSibling:{get:function(){G.currentNode=this;return G.nextSibling()}},innerHTML:{get:function(){return Ra(this,ua)},set:function(b){var c=this.localName==="template"?this.content:this;Ya(c);var e=this.localName||"div";e=this.namespaceURI&&this.namespaceURI!==Xa.namespaceURI?
Xa.createElementNS(this.namespaceURI,e):Xa.createElement(e);e.innerHTML=b;for(b=this.localName==="template"?e.content:e;e=b.__shady_native_firstChild;)c.__shady_native_insertBefore(e,void 0)}},className:{get:function(){return this.getAttribute("class")||""},set:function(b){this.setAttribute("class",b)}}}));E(Element.prototype,"setAttribute getAttribute hasAttribute removeAttribute toggleAttribute focus blur".split(" "));E(Element.prototype,$a);E(HTMLElement.prototype,["focus","blur"]);window.HTMLTemplateElement&&
E(window.HTMLTemplateElement.prototype,["innerHTML"]);Sa?E(DocumentFragment.prototype,Za):Wa(DocumentFragment.prototype,a);E(DocumentFragment.prototype,$a);Sa?(E(Document.prototype,Za),E(Document.prototype,["activeElement"])):Wa(Document.prototype,a);E(Document.prototype,["importNode","getElementById","elementFromPoint",ja()]);E(Document.prototype,$a)};var bb=B({get childNodes(){return this.__shady_childNodes},get firstChild(){return this.__shady_firstChild},get lastChild(){return this.__shady_lastChild},get childElementCount(){return this.__shady_childElementCount},get children(){return this.__shady_children},get firstElementChild(){return this.__shady_firstElementChild},get lastElementChild(){return this.__shady_lastElementChild},get shadowRoot(){return this.__shady_shadowRoot}}),cb=B({get textContent(){return this.__shady_textContent},set textContent(a){this.__shady_textContent=
a},get innerHTML(){return this.__shady_innerHTML},set innerHTML(a){this.__shady_innerHTML=a}}),db=B({get parentElement(){return this.__shady_parentElement},get parentNode(){return this.__shady_parentNode},get nextSibling(){return this.__shady_nextSibling},get previousSibling(){return this.__shady_previousSibling},get nextElementSibling(){return this.__shady_nextElementSibling},get previousElementSibling(){return this.__shady_previousElementSibling},get className(){return this.__shady_className},set className(a){this.__shady_className=
a}});function eb(a){for(var b in a){var c=a[b];c&&(c.enumerable=!1)}}eb(bb);eb(cb);eb(db);var fb=w.j||w.noPatch===!0,gb=fb?function(){}:function(a){var b=u(a);b.mb||(b.mb=!0,xa(a,db))},hb=fb?function(){}:function(a){var b=u(a);b.lb||(b.lb=!0,xa(a,bb),window.customElements&&window.customElements.polyfillWrapFlushCallback&&!w.noPatch||xa(a,cb))};var ib="__eventWrappers"+Date.now(),jb=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),kb=function(){function a(){}var b=!1,c={get capture(){b=!0;return!1}};window.addEventListener("test",a,c);window.removeEventListener("test",a,c);return b}();function lb(a){if(a===null||typeof a!=="object"&&typeof a!=="function"){var b=!!a;var c=!1}else{b=!!a.capture;c=!!a.once;var e=a.I}return{gb:e,capture:b,once:c,fb:kb?a:b}}
var mb={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,
drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},nb={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};function ob(a){return a instanceof Node?a.__shady_getRootNode():a}
function pb(a,b){var c=[],e=a;for(a=ob(a);e;)c.push(e),e=e.__shady_assignedSlot?e.__shady_assignedSlot:e.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&e.host&&(b||e!==a)?e.host:e.__shady_parentNode;c[c.length-1]===document&&c.push(window);return c}function qb(a){a.__composedPath||(a.__composedPath=pb(a.target,!0));return a.__composedPath}function rb(a,b){if(!y)return a;a=pb(a,!0);for(var c=0,e,d=void 0,f,g=void 0;c<b.length;c++)if(e=b[c],f=ob(e),f!==d&&(g=a.indexOf(f),d=f),!y(f)||g>-1)return e}
var sb={get composed(){this.__composed===void 0&&(jb?this.__composed=this.type==="focusin"||this.type==="focusout"||jb(this):this.isTrusted!==!1&&(this.__composed=mb[this.type]));return this.__composed||!1},composedPath:function(){this.__composedPath||(this.__composedPath=pb(this.__target,this.composed));return this.__composedPath},get target(){return rb(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.__relatedTarget)return null;this.__relatedTargetComposedPath||
(this.__relatedTargetComposedPath=pb(this.__relatedTarget,!0));return rb(this.currentTarget||this.__previousCurrentTarget,this.__relatedTargetComposedPath)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.qa=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.qa=this.__immediatePropagationStopped=!0}},tb=w.j&&Object.getOwnPropertyDescriptor(Event.prototype,"eventPhase");
tb&&(Object.defineProperty(sb,"eventPhase",{get:function(){return this.currentTarget===this.target?Event.AT_TARGET:this.__shady_native_eventPhase},enumerable:!0,configurable:!0}),Object.defineProperty(sb,"__shady_native_eventPhase",tb));function ub(a){function b(c,e){c=new a(c,e);c.__composed=e&&!!e.composed;return c}b.__proto__=a;b.prototype=a.prototype;return b}var vb={focus:!0,blur:!0};function wb(a){return a.__target!==a.target||a.__relatedTarget!==a.relatedTarget}
function xb(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var e=0,d;(d=c[e])&&(!wb(a)||a.target!==a.relatedTarget)&&(d.call(b,a),!a.__immediatePropagationStopped);e++);}var yb=(new Event("e")).hasOwnProperty("currentTarget");
function zb(a){a=yb?Object.create(a):a;var b=a.composedPath(),c=b.map(function(n){return rb(n,b)}),e=a.bubbles,d=Object.getOwnPropertyDescriptor(a,"currentTarget");Object.defineProperty(a,"currentTarget",{configurable:!0,enumerable:!0,get:function(){return k}});var f=Event.CAPTURING_PHASE,g=Object.getOwnPropertyDescriptor(a,"eventPhase");Object.defineProperty(a,"eventPhase",{configurable:!0,enumerable:!0,get:function(){return f}});try{for(var h=b.length-1;h>=0;h--){var k=b[h];f=k===c[h]?Event.AT_TARGET:
Event.CAPTURING_PHASE;xb(a,k,"capture");if(a.qa)return}for(h=0;h<b.length;h++){k=b[h];var l=k===c[h];if(l||e)if(f=l?Event.AT_TARGET:Event.BUBBLING_PHASE,xb(a,k,"bubble"),a.qa)break}}finally{yb||(d?Object.defineProperty(a,"currentTarget",d):delete a.currentTarget,g?Object.defineProperty(a,"eventPhase",g):delete a.eventPhase)}}function Ab(a,b,c,e){for(var d=0;d<a.length;d++){var f=a[d],g=f.type,h=f.capture;if(b===f.node&&c===g&&e===h)return d}return-1}
function Bb(a){Fa();return!w.X&&this instanceof Node&&!ra(document,this)?(a.__target||Cb(a,this),zb(a)):this.__shady_native_dispatchEvent(a)}
function Db(a,b,c){var e=this,d=lb(c),f=d.capture,g=d.once,h=d.gb;d=d.fb;if(b){var k=typeof b;if(k==="function"||k==="object")if(k!=="object"||b.handleEvent&&typeof b.handleEvent==="function"){if(nb[a])return this.__shady_native_addEventListener(a,b,d);var l=h||this;if(h=b[ib]){if(Ab(h,l,a,f)>-1)return}else b[ib]=[];h=function(n){g&&e.__shady_removeEventListener(a,b,c);n.__target||Cb(n);if(l!==e){var t=Object.getOwnPropertyDescriptor(n,"currentTarget");Object.defineProperty(n,"currentTarget",{get:function(){return l},
configurable:!0});var C=Object.getOwnPropertyDescriptor(n,"eventPhase");Object.defineProperty(n,"eventPhase",{configurable:!0,enumerable:!0,get:function(){return f?Event.CAPTURING_PHASE:Event.BUBBLING_PHASE}})}n.__previousCurrentTarget=n.currentTarget;if(!y(l)&&l.localName!=="slot"||n.composedPath().indexOf(l)!=-1)if(n.composed||n.composedPath().indexOf(l)>-1)if(wb(n)&&n.target===n.relatedTarget)n.eventPhase===Event.BUBBLING_PHASE&&n.stopImmediatePropagation();else if(n.eventPhase===Event.CAPTURING_PHASE||
n.bubbles||n.target===l||l instanceof Window){var qa=k==="function"?b.call(l,n):b.handleEvent&&b.handleEvent(n);l!==e&&(t?(Object.defineProperty(n,"currentTarget",t),t=null):delete n.currentTarget,C?(Object.defineProperty(n,"eventPhase",C),C=null):delete n.eventPhase);return qa}};b[ib].push({node:l,type:a,capture:f,Fc:h});this.__handlers=this.__handlers||{};this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]};this.__handlers[a][f?"capture":"bubble"].push(h);vb[a]||this.__shady_native_addEventListener(a,
h,d)}}}function Eb(a,b,c){if(b){var e=lb(c);c=e.capture;var d=e.gb;e=e.fb;if(nb[a])return this.__shady_native_removeEventListener(a,b,e);var f=d||this;d=void 0;var g=null;try{g=b[ib]}catch(h){}g&&(f=Ab(g,f,a,c),f>-1&&(d=g.splice(f,1)[0].Fc,g.length||(b[ib]=void 0)));this.__shady_native_removeEventListener(a,d||b,e);d&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][c?"capture":"bubble"],b=a.indexOf(d),b>-1&&a.splice(b,1))}}
function Fb(){for(var a in vb)window.__shady_native_addEventListener(a,function(b){b.__target||(Cb(b),zb(b))},!0)}var Gb=B(sb);function Cb(a,b){b=b===void 0?a.target:b;a.__target=b;a.__relatedTarget=a.relatedTarget;if(w.j){b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__shady_patchedProto")){var c=Object.create(b);c.__shady_sourceProto=b;A(c,Gb);b.__shady_patchedProto=c}a.__proto__=b.__shady_patchedProto}else A(a,Gb)}var Hb=ub(Event),Ib=ub(CustomEvent),Jb=ub(MouseEvent);
function Kb(){if(!jb&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var b=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.__shady_dispatchEvent(b)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}}
var Lb=Object.getOwnPropertyNames(Element.prototype).filter(function(a){return a.substring(0,2)==="on"}),Mb=Object.getOwnPropertyNames(HTMLElement.prototype).filter(function(a){return a.substring(0,2)==="on"});function Nb(a){return{set:function(b){var c=u(this),e=a.substring(2);c.H||(c.H={});c.H[a]&&this.removeEventListener(e,c.H[a]);this.__shady_addEventListener(e,b);c.H[a]=b},get:function(){var b=v(this);return b&&b.H&&b.H[a]},configurable:!0}};function Ob(a,b){return{index:a,Y:[],la:b}}
function Pb(a,b,c,e){var d=0,f=0,g=0,h=0,k=Math.min(b-d,e-f);if(d==0&&f==0)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&e==c.length){h=a.length;for(var l=c.length,n=0;n<k-g&&Qb(a[--h],c[--l]);)n++;h=n}d+=g;f+=g;b-=h;e-=h;if(b-d==0&&e-f==0)return[];if(d==b){for(b=Ob(d,0);f<e;)b.Y.push(c[f++]);return[b]}if(f==e)return[Ob(d,b-d)];k=d;g=f;e=e-g+1;h=b-k+1;b=Array(e);for(l=0;l<e;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<e;l++)for(n=1;n<h;n++)if(a[k+n-1]===c[g+l-1])b[l][n]=
b[l-1][n-1];else{var t=b[l-1][n]+1,C=b[l][n-1]+1;b[l][n]=t<C?t:C}k=b.length-1;g=b[0].length-1;e=b[k][g];for(a=[];k>0||g>0;)k==0?(a.push(2),g--):g==0?(a.push(3),k--):(h=b[k-1][g-1],l=b[k-1][g],n=b[k][g-1],t=l<n?l<h?l:h:n<h?n:h,t==h?(h==e?a.push(0):(a.push(1),e=h),k--,g--):t==l?(a.push(3),k--,e=l):(a.push(2),g--,e=n));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);d++;f++;break;case 1:b||(b=Ob(d,0));b.la++;d++;b.Y.push(c[f]);f++;break;case 2:b||(b=Ob(d,
0));b.la++;d++;break;case 3:b||(b=Ob(d,0)),b.Y.push(c[f]),f++}b&&k.push(b);return k}function Qb(a,b){return a===b};var Rb=B({dispatchEvent:Bb,addEventListener:Db,removeEventListener:Eb});var Sb=null;function H(){Sb||(Sb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return Sb||null}function Tb(a,b,c){var e=H();return e&&b==="class"?(e.setElementClass(a,c),!0):!1}function Ub(a,b){var c=H();c&&c.unscopeNode(a,b)}function Vb(a,b){var c=H();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)c=c&&Vb(a,b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}
function Wb(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=H();return b?b.currentScopeForNode(a):""}function Xb(a,b){if(a)for(a.nodeType===Node.ELEMENT_NODE&&b(a),a=a.__shady_firstChild;a;a=a.__shady_nextSibling)a.nodeType===Node.ELEMENT_NODE&&Xb(a,b)};var Yb=window.document,Zb=w.X,$b=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),ac=$b&&$b.get;function bc(a){for(var b;b=a.__shady_firstChild;)a.__shady_removeChild(b)}function cc(a){var b=v(a);if(b&&b.pa!==void 0)for(b=a.__shady_firstChild;b;b=b.__shady_nextSibling)cc(b);if(a=v(a))a.pa=void 0}function dc(a){var b=a;if(a&&a.localName==="slot"){var c=v(a);(c=c&&c.P)&&(b=c.length?c[0]:dc(a.__shady_nextSibling))}return b}
function ec(a,b,c){if(a=(a=v(a))&&a.W){if(b)if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE)for(var e=0,d=b.childNodes.length;e<d;e++)a.addedNodes.push(b.childNodes[e]);else a.addedNodes.push(b);c&&a.removedNodes.push(c);Ha(a)}}
var jc=B({get parentNode(){var a=v(this);a=a&&a.parentNode;return a!==void 0?a:this.__shady_native_parentNode},get firstChild(){var a=v(this);a=a&&a.firstChild;return a!==void 0?a:this.__shady_native_firstChild},get lastChild(){var a=v(this);a=a&&a.lastChild;return a!==void 0?a:this.__shady_native_lastChild},get nextSibling(){var a=v(this);a=a&&a.nextSibling;return a!==void 0?a:this.__shady_native_nextSibling},get previousSibling(){var a=v(this);a=a&&a.previousSibling;return a!==void 0?a:this.__shady_native_previousSibling},
get childNodes(){if(x(this)){var a=v(this);if(!a.childNodes){a.childNodes=[];for(var b=this.__shady_firstChild;b;b=b.__shady_nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=this.__shady_native_childNodes;c.item=function(e){return c[e]};return c},get parentElement(){var a=v(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return a!==void 0?a:this.__shady_native_parentElement},get isConnected(){if(ac&&ac.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;
var a=this.ownerDocument;if(a===null||ra(a,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.__shady_parentNode||(y(a)?a.host:void 0);return!!(a&&a instanceof Document)},get textContent(){if(x(this)){for(var a=[],b=this.__shady_firstChild;b;b=b.__shady_nextSibling)b.nodeType!==Node.COMMENT_NODE&&a.push(b.__shady_textContent);return a.join("")}return this.__shady_native_textContent},set textContent(a){if(typeof a==="undefined"||a===null)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!x(this)&&
w.j){var b=this.__shady_firstChild;(b!=this.__shady_lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&bc(this);this.__shady_native_textContent=a}else bc(this),(a.length>0||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_insertBefore(document.createTextNode(a));break;default:this.nodeValue=a}},insertBefore:function(a,b){if(this.ownerDocument!==Yb&&a.ownerDocument!==Yb)return this.__shady_native_insertBefore(a,b),a;if(a===this)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");
if(b){var c=v(b);c=c&&c.parentNode;if(c!==void 0&&c!==this||c===void 0&&b.__shady_native_parentNode!==this)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(b===a)return a;ec(this,a);var e=[],d=(c=fc(this))?c.host.localName:Wb(this),f=a.__shady_parentNode;if(f){var g=Wb(a);var h=!!c||!fc(a)||Zb&&this.__noInsertionPoint!==void 0;f.__shady_removeChild(a,h)}f=!0;var k=(!Zb||a.__noInsertionPoint===void 0&&this.__noInsertionPoint===
void 0)&&!Vb(a,d),l=c&&!a.__noInsertionPoint&&(!Zb||a.nodeType===Node.DOCUMENT_FRAGMENT_NODE);if(l||k)k&&(g=g||Wb(a)),Xb(a,function(n){l&&n.localName==="slot"&&e.push(n);if(k){var t=g;H()&&(t&&Ub(n,t),(t=H())&&t.scopeNode(n,d))}});e.length&&(c.Ga(e),c.u());x(this)&&(hc(a,this,b),h=v(this),h.root?(f=!1,ka(this)&&h.root.u()):c&&this.localName==="slot"&&(f=!1,c.u()));f?(c=y(this)?this.host:this,b?(b=dc(b),c.__shady_native_insertBefore(a,b)):c.__shady_native_appendChild(a)):a.ownerDocument!==this.ownerDocument&&
this.ownerDocument.adoptNode(a);return a},appendChild:function(a){if(this!=a||!y(a))return this.__shady_insertBefore(a)},removeChild:function(a,b){b=b===void 0?!1:b;if(this.ownerDocument!==Yb)return this.__shady_native_removeChild(a);if(a.__shady_parentNode!==this)throw Error("The node to be removed is not a child of this node: "+a);ec(this,null,a);var c=fc(a),e=c&&c.Rb(a),d=v(this);if(x(this)&&(ic(a,this),ka(this))){d.root.u();var f=!0}if(H()&&!b&&c&&a.nodeType!==Node.TEXT_NODE){var g=Wb(a);Xb(a,
function(h){Ub(h,g)})}cc(a);c&&((b=this.localName==="slot")&&(f=!0),(e||b)&&c.u());f||(f=y(this)?this.host:this,(!d.root&&a.localName!=="slot"||f===a.__shady_native_parentNode)&&f.__shady_native_removeChild(a));return a},replaceChild:function(a,b){this.__shady_insertBefore(a,b);this.__shady_removeChild(b);return a},cloneNode:function(a){if(this.localName=="template")return this.__shady_native_cloneNode(a);var b=this.__shady_native_cloneNode(!1);if(a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.__shady_firstChild;
for(var c;a;a=a.__shady_nextSibling)c=a.__shady_cloneNode(!0),b.__shady_appendChild(c)}return b},getRootNode:function(a){if(this&&this.nodeType){var b=u(this),c=b.pa;c===void 0&&(y(this)?(c=this,b.pa=c):(c=(c=this.__shady_parentNode)?c.__shady_getRootNode(a):this,document.documentElement.__shady_native_contains(this)&&(b.pa=c)));return c}},contains:function(a){return sa(this,a)}});var kc=B({get assignedSlot(){var a=this.__shady_parentNode;(a=a&&a.__shady_shadowRoot)&&a.ga();return(a=v(this))&&a.assignedSlot||null}});/*

 Copyright (c) 2022 The Polymer Project Authors
 SPDX-License-Identifier: BSD-3-Clause
*/
var lc=new Map;[["(",{end:")",oa:!0}],["[",{end:"]",oa:!0}],['"',{end:'"',oa:!1}],["'",{end:"'",oa:!1}]].forEach(function(a){var b=p(a);a=b.next().value;b=b.next().value;lc.set(a,b)});function mc(a,b,c,e){for(e=e===void 0?!0:e;b<a.length;b++)if(a[b]==="\\"&&b<a.length-1&&a[b+1]!=="\n")b++;else{if(c.indexOf(a[b])!==-1)return b;if(e&&lc.has(a[b])){var d=lc.get(a[b]);b=mc(a,b+1,[d.end],d.oa)}}return a.length}
function nc(a){function b(){if(e.length>0){for(;e[e.length-1]===" ";)e.pop();c.push({cb:e.filter(function(k,l){return l%2===0}),lc:e.filter(function(k,l){return l%2===1})});e.length=0}}for(var c=[],e=[],d=0;d<a.length;){var f=e[e.length-1],g=mc(a,d,[","," ",">","+","~"]),h=g===d?a[d]:a.substring(d,g);if(h===",")b();else if([void 0," ",">","+","~"].indexOf(f)===-1||h!==" ")f===" "&&[">","+","~"].indexOf(h)!==-1?e[e.length-1]=h:e.push(h);d=g+(g===d?1:0)}b();return c};function oc(a,b,c){var e=[];pc(a,b,c,e);return e}function pc(a,b,c,e){for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling){var d;if(d=a.nodeType===Node.ELEMENT_NODE){d=a;var f=b,g=c,h=e,k=f(d);k&&h.push(d);g&&g(k)?d=k:(pc(d,f,g,h),d=void 0)}if(d)break}}
var qc={get firstElementChild(){var a=v(this);if(a&&a.firstChild!==void 0){for(a=this.__shady_firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_firstElementChild},get lastElementChild(){var a=v(this);if(a&&a.lastChild!==void 0){for(a=this.__shady_lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_lastElementChild},get children(){return x(this)?ta(Array.prototype.filter.call(va(this),function(a){return a.nodeType===
Node.ELEMENT_NODE})):this.__shady_native_children},get childElementCount(){var a=this.__shady_children;return a?a.length:0}},rc=B((qc.append=function(){this.__shady_insertBefore(D.apply(null,q(r.apply(0,arguments))),null)},qc.prepend=function(){this.__shady_insertBefore(D.apply(null,q(r.apply(0,arguments))),this.__shady_firstChild)},qc.replaceChildren=function(){for(var a=r.apply(0,arguments),b;(b=this.__shady_firstChild)!==null;)this.__shady_removeChild(b);this.__shady_insertBefore(D.apply(null,
q(a)),null)},qc));
function sc(a,b){function c(d,f){return(d===a||f.indexOf(":scope")===-1)&&la.call(d,f)}var e=nc(b);if(e.length<1)return[];for(b=Aa(oc(a,function(){return!0}).map(function(d){return Aa(e.map(function(f){var g=f.cb,h=g.length-1;return c(d,g[h])?{target:d,U:f,V:d,index:h}:[]}))}));b.some(function(d){return d.index>0});)b=Aa(b.map(function(d){if(d.index<=0)return d;var f=d.target,g=d.V,h=d.U;d=d.index-1;var k=h.lc[d],l=h.cb[d];if(k===" "){k=[];for(g=g.__shady_parentElement;g;g=g.__shady_parentElement)c(g,l)&&
k.push({target:f,U:h,V:g,index:d});return k}if(k===">")return g=g.__shady_parentElement,c(g,l)?{target:f,U:h,V:g,index:d}:[];if(k==="+")return(g=g.__shady_previousElementSibling)&&c(g,l)?{target:f,U:h,V:g,index:d}:[];if(k==="~"){k=[];for(g=g.__shady_previousElementSibling;g;g=g.__shady_previousElementSibling)c(g,l)&&k.push({target:f,U:h,V:g,index:d});return k}throw Error("Unrecognized combinator: '"+k+"'.");}));return Ba(b.map(function(d){return d.target}))}
var I=w.querySelectorImplementation,tc=B({querySelector:function(a){if(I==="native"){var b=Array.prototype.slice.call((this instanceof ShadowRoot?this.host:this).__shady_native_querySelectorAll(a)),c=this.__shady_getRootNode();b=p(b);for(var e=b.next();!e.done;e=b.next())if(e=e.value,e.__shady_getRootNode()==c)return e;return null}if(I==="selectorEngine")return sc(this,a)[0]||null;if(I===void 0)return oc(this,function(d){return la.call(d,a)},function(d){return!!d})[0]||null;throw Error("Unrecognized value of ShadyDOM.querySelectorImplementation: '"+
(I+"'"));},querySelectorAll:function(a,b){if(b||I==="native"){b=Array.prototype.slice.call((this instanceof ShadowRoot?this.host:this).__shady_native_querySelectorAll(a));var c=this.__shady_getRootNode();return ta(b.filter(function(e){return e.__shady_getRootNode()==c}))}if(I==="selectorEngine")return ta(sc(this,a));if(I===void 0)return ta(oc(this,function(e){return la.call(e,a)}));throw Error("Unrecognized value of ShadyDOM.querySelectorImplementation: '"+(I+"'"));}}),uc=w.X&&!w.noPatch?ya({},rc):
rc;ya(rc,tc);/*

Copyright (c) 2020 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var vc=B({after:function(){var a=this.__shady_parentNode;if(a!==null){var b=this.__shady_nextSibling;a.__shady_insertBefore(D.apply(null,q(r.apply(0,arguments))),b)}},before:function(){var a=this.__shady_parentNode;a!==null&&a.__shady_insertBefore(D.apply(null,q(r.apply(0,arguments))),this)},remove:function(){var a=this.__shady_parentNode;a!==null&&a.__shady_removeChild(this)},replaceWith:function(){var a=r.apply(0,arguments),b=this.__shady_parentNode;if(b!==null){var c=this.__shady_nextSibling;b.__shady_removeChild(this);
b.__shady_insertBefore(D.apply(null,q(a)),c)}}});var wc=window.document;function xc(a,b){b==="slot"?(a=a.__shady_parentNode,ka(a)&&v(a).root.u()):a.localName==="slot"&&b==="name"&&(b=fc(a))&&(b.fc(a),b.u())}
var yc=B({get previousElementSibling(){var a=v(this);if(a&&a.previousSibling!==void 0){for(a=this.__shady_previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_previousElementSibling},get nextElementSibling(){var a=v(this);if(a&&a.nextSibling!==void 0){for(a=this.__shady_nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_nextElementSibling},get slot(){return this.getAttribute("slot")},
set slot(a){this.__shady_setAttribute("slot",a)},get className(){return this.getAttribute("class")||""},set className(a){this.__shady_setAttribute("class",a)},setAttribute:function(a,b){this.ownerDocument!==wc?this.__shady_native_setAttribute(a,b):Tb(this,a,b)||(this.__shady_native_setAttribute(a,b),xc(this,a))},removeAttribute:function(a){this.ownerDocument!==wc?this.__shady_native_removeAttribute(a):Tb(this,a,"")?this.getAttribute(a)===""&&this.__shady_native_removeAttribute(a):(this.__shady_native_removeAttribute(a),
xc(this,a))},toggleAttribute:function(a,b){if(this.ownerDocument!==wc)return this.__shady_native_toggleAttribute(a,b);if(!Tb(this,a,""))return b=this.__shady_native_toggleAttribute(a,b),xc(this,a),b;if(this.getAttribute(a)===""&&!b)return this.__shady_native_toggleAttribute(a,b)}});w.X||Lb.forEach(function(a){yc[a]=Nb(a)});
var Cc=B({attachShadow:function(a){if(!this)throw Error("Must provide a host.");if(!a)throw Error("Not enough arguments.");if(a.shadyUpgradeFragment&&!w.jb){var b=a.shadyUpgradeFragment;b.__proto__=ShadowRoot.prototype;b.Pa(this,a);zc(b,b);a=b.__noInsertionPoint?null:b.querySelectorAll("slot");b.__noInsertionPoint=void 0;a&&a.length&&(b.Ga(a),b.u());b.host.__shady_native_appendChild(b)}else b=new Ac(Bc,this,a);return this.__CE_shadowRoot=b},get shadowRoot(){var a=v(this);return a&&a.vc||null}});
ya(yc,Cc);var Dc=document.implementation.createHTMLDocument("inert"),Ec=B({get innerHTML(){return x(this)?Ra(this.localName==="template"?this.content:this,va):this.__shady_native_innerHTML},set innerHTML(a){if(this.localName==="template")this.__shady_native_innerHTML=a;else{bc(this);var b=this.localName||"div";b=this.namespaceURI&&this.namespaceURI!==Dc.namespaceURI?Dc.createElementNS(this.namespaceURI,b):Dc.createElement(b);for(w.j?b.__shady_native_innerHTML=a:b.innerHTML=a;a=b.__shady_firstChild;)this.__shady_insertBefore(a)}}});var Fc=B({blur:function(){var a=v(this);(a=(a=a&&a.root)&&a.activeElement)?a.__shady_blur():this.__shady_native_blur()}});w.X||Mb.forEach(function(a){Fc[a]=Nb(a)});var Gc=B({assignedNodes:function(a){if(this.localName==="slot"){var b=this.__shady_getRootNode();b&&y(b)&&b.ga();return(b=v(this))?(a&&a.flatten?b.P:b.assignedNodes)||[]:[]}},addEventListener:function(a,b,c){if(this.localName!=="slot"||a==="slotchange")Db.call(this,a,b,c);else{typeof c!=="object"&&(c={capture:!!c});var e=this.__shady_parentNode;if(!e)throw Error("ShadyDOM cannot attach event to slot unless it has a `parentNode`");c.I=this;e.__shady_addEventListener(a,b,c)}},removeEventListener:function(a,
b,c){if(this.localName!=="slot"||a==="slotchange")Eb.call(this,a,b,c);else{typeof c!=="object"&&(c={capture:!!c});var e=this.__shady_parentNode;if(!e)throw Error("ShadyDOM cannot attach event to slot unless it has a `parentNode`");c.I=this;e.__shady_removeEventListener(a,b,c)}}});var Hc=B({getElementById:function(a){return a===""?null:oc(this,function(b){return b.id==a},function(b){return!!b})[0]||null}});function Ic(a,b){for(var c;b&&!a.has(c=b.__shady_getRootNode());)b=c.host;return b}function Jc(a){var b=new Set;for(b.add(a);y(a)&&a.host;)a=a.host.__shady_getRootNode(),b.add(a);return b}
var Kc="__shady_native_"+ja(),Lc=B({get activeElement(){var a=w.j?document.__shady_native_activeElement:document.activeElement;if(!a||!a.nodeType)return null;var b=!!y(this);if(!(this===document||b&&this.host!==a&&this.host.__shady_native_contains(a)))return null;for(b=fc(a);b&&b!==this;)a=b.host,b=fc(a);return this===document?b?null:a:b===this?a:null},elementsFromPoint:function(a,b){a=document[Kc](a,b);if(this===document&&w.useNativeDocumentEFP)return a;a=[].slice.call(a);b=Jc(this);for(var c=new Set,
e=0;e<a.length;e++)c.add(Ic(b,a[e]));var d=[];c.forEach(function(f){return d.push(f)});return d},elementFromPoint:function(a,b){return this===document&&w.useNativeDocumentEFP?this.__shady_native_elementFromPoint(a,b):this.__shady_elementsFromPoint(a,b)[0]||null}});var Mc=window.document,Nc=B({importNode:function(a,b){if(a.ownerDocument!==Mc||a.localName==="template")return this.__shady_native_importNode(a,b);var c=this.__shady_native_importNode(a,!1);if(b)for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)b=this.__shady_importNode(a,!0),c.__shady_appendChild(b);return c}});var Oc=B({dispatchEvent:Bb,addEventListener:Db.bind(window),removeEventListener:Eb.bind(window)});var Pc={};Object.getOwnPropertyDescriptor(HTMLElement.prototype,"parentElement")&&(Pc.parentElement=jc.parentElement);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"contains")&&(Pc.contains=jc.contains);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"children")&&(Pc.children=rc.children);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&(Pc.innerHTML=Ec.innerHTML);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"className")&&(Pc.className=yc.className);
var J={EventTarget:[Rb],Node:[jc,window.EventTarget?null:Rb],Text:[kc],Comment:[kc],CDATASection:[kc],ProcessingInstruction:[kc],Element:[yc,rc,vc,kc,!w.j||"innerHTML"in Element.prototype?Ec:null,window.HTMLSlotElement?null:Gc],HTMLElement:[Fc,Pc],HTMLSlotElement:[Gc],DocumentFragment:[uc,Hc],Document:[Nc,uc,Hc,Lc],Window:[Oc],CharacterData:[vc],XMLHttpRequest:[window.EventTarget?null:Rb]},Qc=w.j?null:["innerHTML","textContent"];
function K(a,b,c,e){b.forEach(function(d){return a&&d&&A(a,d,c,e)})}function Rc(a){var b=a?null:Qc,c;for(c in J)K(window[c]&&window[c].prototype,J[c],a,b)}["Text","Comment","CDATASection","ProcessingInstruction"].forEach(function(a){var b=window[a],c=Object.create(b.prototype);c.__shady_protoIsPatched=!0;K(c,J.EventTarget);K(c,J.Node);J[a]&&K(c,J[a]);b.prototype.__shady_patchedProto=c});
function Sc(a){a.__shady_protoIsPatched=!0;K(a,J.EventTarget);K(a,J.Node);K(a,J.Element);K(a,J.HTMLElement);K(a,J.HTMLSlotElement);return a};var Tc=w.Da,Uc=w.j;function Vc(a,b){if(Tc&&!a.__shady_protoIsPatched&&!y(a)){var c=Object.getPrototypeOf(a),e=c.hasOwnProperty("__shady_patchedProto")&&c.__shady_patchedProto;e||(e=Object.create(c),Sc(e),c.__shady_patchedProto=e);Object.setPrototypeOf(a,e)}Uc||(b===1?gb(a):b===2&&hb(a))}
function Wc(a,b,c,e){Vc(a,1);e=e||null;var d=u(a),f=e?u(e):null;d.previousSibling=e?f.previousSibling:b.__shady_lastChild;if(f=v(d.previousSibling))f.nextSibling=a;if(f=v(d.nextSibling=e))f.previousSibling=a;d.parentNode=b;e?e===c.firstChild&&(c.firstChild=a):(c.lastChild=a,c.firstChild||(c.firstChild=a));c.childNodes=null}
function hc(a,b,c){Vc(b,2);var e=u(b);e.firstChild!==void 0&&(e.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE)for(a=a.__shady_native_firstChild;a;a=a.__shady_native_nextSibling)Wc(a,b,e,c);else Wc(a,b,e,c)}
function ic(a,b){var c=u(a);b=u(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var e=c.nextSibling;a&&(u(a).nextSibling=e);e&&(u(e).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;b.childNodes!==void 0&&(b.childNodes=null)}
function zc(a,b){var c=u(a);if(b||c.firstChild===void 0){c.childNodes=null;var e=c.firstChild=a.__shady_native_firstChild;c.lastChild=a.__shady_native_lastChild;Vc(a,2);c=e;for(e=void 0;c;c=c.__shady_native_nextSibling){var d=u(c);d.parentNode=b||a;d.nextSibling=c.__shady_native_nextSibling;d.previousSibling=e||null;e=c;Vc(c,1)}}};var Xc=B({addEventListener:function(a,b,c){typeof c!=="object"&&(c={capture:!!c});c.I=c.I||this;this.host.__shady_addEventListener(a,b,c)},removeEventListener:function(a,b,c){typeof c!=="object"&&(c={capture:!!c});c.I=c.I||this;this.host.__shady_removeEventListener(a,b,c)}});function Yc(a,b){A(a,Xc,b);A(a,Lc,b);A(a,Ec,b);A(a,rc,b);w.noPatch&&!b?(A(a,jc,b),A(a,Hc,b)):w.j||(A(a,db),A(a,bb),A(a,cb))};var Bc={},L=w.deferConnectionCallbacks&&document.readyState==="loading",Zc;function $c(a){var b=[];do b.unshift(a);while(a=a.__shady_parentNode);return b}function Ac(a,b,c){if(a!==Bc)throw new TypeError("Illegal constructor");this.g=null;this.Pa(b,c)}m=Ac.prototype;
m.Pa=function(a,b){this.host=a;this.mode=b&&b.mode;zc(this.host);a=u(this.host);a.root=this;a.vc=this.mode!=="closed"?this:null;a=u(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;if(w.preferPerformance)for(;a=this.host.__shady_native_firstChild;)this.host.__shady_native_removeChild(a);else this.u()};m.u=function(){var a=this;this.N||(this.N=!0,Ea(function(){return a.ga()}))};m.Fb=function(){for(var a,b=this;b;)b.N&&(a=b),b=b.Eb();return a};
m.Eb=function(){var a=this.host.__shady_getRootNode();if(y(a)){var b=v(this.host);if(b&&b.ba>0)return a}};m.ga=function(){var a=this.N&&this.Fb();a&&a._renderSelf()};m.Ab=function(){!this.Oa&&this.N&&this.ga()};
m._renderSelf=function(){var a=L;L=!0;this.N=!1;this.g&&(this.ub(),this.sb());if(!w.preferPerformance&&!this.Oa)for(var b=this.host.__shady_firstChild;b;b=b.__shady_nextSibling){var c=v(b);b.__shady_native_parentNode!==this.host||b.localName!=="slot"&&c.assignedSlot||this.host.__shady_native_removeChild(b)}this.Oa=!0;L=a;Zc&&Zc()};
m.ub=function(){this.ka();for(var a=0,b;a<this.g.length;a++)b=this.g[a],this.rb(b);for(a=this.host.__shady_firstChild;a;a=a.__shady_nextSibling)this.Ja(a);for(a=0;a<this.g.length;a++){b=this.g[a];var c=v(b);if(!c.assignedNodes.length)for(var e=b.__shady_firstChild;e;e=e.__shady_nextSibling)this.Ja(e,b);(e=(e=v(b.__shady_parentNode))&&e.root)&&(e.Na()||e.N)&&e._renderSelf();this.Fa(c.P,c.assignedNodes);if(e=c.Ta){for(var d=0;d<e.length;d++)v(e[d]).wa=null;c.Ta=null;e.length>c.assignedNodes.length&&
(c.Ba=!0)}c.Ba&&(c.Ba=!1,this.La(b))}};m.Ja=function(a,b){var c=u(a),e=c.wa;c.wa=null;b||(b=(b=this.i[a.__shady_slot||"__catchall"])&&b[0]);b?(u(b).assignedNodes.push(a),c.assignedSlot=b):c.assignedSlot=void 0;e!==c.assignedSlot&&c.assignedSlot&&(u(c.assignedSlot).Ba=!0)};m.rb=function(a){var b=v(a),c=b.assignedNodes;b.assignedNodes=[];b.P=[];if(b.Ta=c)for(b=0;b<c.length;b++){var e=v(c[b]);e.wa=e.assignedSlot;e.assignedSlot===a&&(e.assignedSlot=null)}};
m.Fa=function(a,b){for(var c=0,e=void 0;c<b.length&&(e=b[c]);c++)if(e.localName=="slot"){var d=v(e).assignedNodes;d&&d.length&&this.Fa(a,d)}else a.push(b[c])};m.La=function(a){a.__shady_native_dispatchEvent(new Event("slotchange"));a=v(a);a.assignedSlot&&this.La(a.assignedSlot)};m.sb=function(){for(var a=this.g,b=[],c=0;c<a.length;c++){var e=a[c].__shady_parentNode,d=v(e);d&&d.root||!(b.indexOf(e)<0)||b.push(e)}for(a=0;a<b.length;a++)c=b[a],this.ec(c===this?this.host:c,this.tb(c))};
m.tb=function(a){var b=[];for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)if(this.Ib(a))for(var c=v(a).P,e=0;e<c.length;e++)b.push(c[e]);else b.push(a);return b};m.Ib=function(a){return a.localName=="slot"};
m.ec=function(a,b){for(var c=ua(a),e=Pb(b,b.length,c,c.length),d=0,f=0,g=void 0;d<e.length&&(g=e[d]);d++){for(var h=0,k=void 0;h<g.Y.length&&(k=g.Y[h]);h++)k.__shady_native_parentNode===a&&a.__shady_native_removeChild(k),c.splice(g.index+f,1);f-=g.la}d=0;for(f=void 0;d<e.length&&(f=e[d]);d++)for(g=c[f.index],h=f.index;h<f.index+f.la;h++)k=b[h],a.__shady_native_insertBefore(k,g),c.splice(h,0,k)};m.zb=function(){this.G=this.G||[];this.g=this.g||[];this.i=this.i||{}};
m.Ga=function(a){this.zb();this.G.push.apply(this.G,q(a))};m.ka=function(){this.G&&this.G.length&&(this.Mb(this.G),this.G=[])};m.Mb=function(a){for(var b,c=0;c<a.length;c++){var e=a[c];zc(e);var d=e.__shady_parentNode;zc(d);d=v(d);d.ba=(d.ba||0)+1;d=this.Ra(e);this.i[d]?(b=b||{},b[d]=!0,this.i[d].push(e)):this.i[d]=[e];this.g.push(e)}if(b)for(var f in b)this.i[f]=this.Wa(this.i[f])};m.Ra=function(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.nb=b};
m.Wa=function(a){return a.sort(function(b,c){b=$c(b);for(var e=$c(c),d=0;d<b.length;d++){c=b[d];var f=e[d];if(c!==f)return b=va(c.__shady_parentNode),b.indexOf(c)-b.indexOf(f)}})};m.Rb=function(a){if(this.g){this.ka();var b=this.i,c;for(c in b)for(var e=b[c],d=0;d<e.length;d++){var f=e[d];if(sa(a,f)){e.splice(d,1);var g=this.g.indexOf(f);g>=0&&(this.g.splice(g,1),(g=v(f.__shady_parentNode))&&g.ba&&g.ba--);d--;this.Sb(f);g=!0}}return g}};
m.fc=function(a){if(this.g){this.ka();var b=a.nb,c=this.Ra(a);if(c!==b){b=this.i[b];var e=b.indexOf(a);e>=0&&b.splice(e,1);b=this.i[c]||(this.i[c]=[]);b.push(a);b.length>1&&(this.i[c]=this.Wa(b))}}};m.Sb=function(a){a=v(a);var b=a.P;if(b)for(var c=0;c<b.length;c++){var e=b[c],d=e.__shady_native_parentNode;d&&d.__shady_native_removeChild(e)}a.P=[];a.assignedNodes=[]};m.Na=function(){this.ka();return!(!this.g||!this.g.length)};
(function(a){a.__proto__=DocumentFragment.prototype;Yc(a,"__shady_");Yc(a);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})})(Ac.prototype);
if(window.customElements&&window.customElements.define&&w.inUse&&!w.preferPerformance){var ad=new Map;Zc=function(){var a=[];ad.forEach(function(e,d){a.push([d,e])});ad.clear();for(var b=0;b<a.length;b++){var c=a[b][0];a[b][1]?c.__shadydom_connectedCallback():c.__shadydom_disconnectedCallback()}};L&&document.addEventListener("readystatechange",function(){L=!1;Zc()},{once:!0});var bd=function(a,b,c){var e=0,d="__isConnected"+e++;if(b||c)a.prototype.connectedCallback=a.prototype.__shadydom_connectedCallback=
function(){L?ad.set(this,!0):this[d]||(this[d]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.__shadydom_disconnectedCallback=function(){L?this.isConnected||ad.set(this,!1):this[d]&&(this[d]=!1,c&&c.call(this))};return a},cd=window.customElements.define,dd=function(a,b){var c=b.prototype.connectedCallback,e=b.prototype.disconnectedCallback;cd.call(window.customElements,a,bd(b,c,e));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=e};window.customElements.define=
dd;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:dd,configurable:!0})}function fc(a){a=a.__shady_getRootNode();if(y(a))return a};function ed(a){this.node=a}m=ed.prototype;m.addEventListener=function(a,b,c){return this.node.__shady_addEventListener(a,b,c)};m.removeEventListener=function(a,b,c){return this.node.__shady_removeEventListener(a,b,c)};m.appendChild=function(a){return this.node.__shady_appendChild(a)};m.insertBefore=function(a,b){return this.node.__shady_insertBefore(a,b)};m.removeChild=function(a){return this.node.__shady_removeChild(a)};m.replaceChild=function(a,b){return this.node.__shady_replaceChild(a,b)};
m.cloneNode=function(a){return this.node.__shady_cloneNode(a)};m.getRootNode=function(a){return this.node.__shady_getRootNode(a)};m.contains=function(a){return this.node.__shady_contains(a)};m.dispatchEvent=function(a){return this.node.__shady_dispatchEvent(a)};m.setAttribute=function(a,b){this.node.__shady_setAttribute(a,b)};m.getAttribute=function(a){return this.node.__shady_native_getAttribute(a)};m.hasAttribute=function(a){return this.node.__shady_native_hasAttribute(a)};m.removeAttribute=function(a){this.node.__shady_removeAttribute(a)};
m.toggleAttribute=function(a,b){return this.node.__shady_toggleAttribute(a,b)};m.attachShadow=function(a){return this.node.__shady_attachShadow(a)};m.focus=function(){this.node.__shady_native_focus()};m.blur=function(){this.node.__shady_blur()};m.importNode=function(a,b){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_importNode(a,b)};m.getElementById=function(a){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_getElementById(a)};
m.elementsFromPoint=function(a,b){return this.node.__shady_elementsFromPoint(a,b)};m.elementFromPoint=function(a,b){return this.node.__shady_elementFromPoint(a,b)};m.querySelector=function(a){return this.node.__shady_querySelector(a)};m.querySelectorAll=function(a,b){return this.node.__shady_querySelectorAll(a,b)};m.assignedNodes=function(a){if(this.node.localName==="slot")return this.node.__shady_assignedNodes(a)};m.append=function(){return this.node.__shady_append.apply(this.node,q(r.apply(0,arguments)))};
m.prepend=function(){return this.node.__shady_prepend.apply(this.node,q(r.apply(0,arguments)))};m.replaceChildren=function(){return this.node.__shady_replaceChildren.apply(this.node,q(r.apply(0,arguments)))};m.after=function(){return this.node.__shady_after.apply(this.node,q(r.apply(0,arguments)))};m.before=function(){return this.node.__shady_before.apply(this.node,q(r.apply(0,arguments)))};m.remove=function(){return this.node.__shady_remove()};
m.replaceWith=function(){return this.node.__shady_replaceWith.apply(this.node,q(r.apply(0,arguments)))};
ca.Object.defineProperties(ed.prototype,{activeElement:{configurable:!0,enumerable:!0,get:function(){if(y(this.node)||this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_activeElement}},_activeElement:{configurable:!0,enumerable:!0,get:function(){return this.activeElement}},host:{configurable:!0,enumerable:!0,get:function(){if(y(this.node))return this.node.host}},parentNode:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_parentNode}},firstChild:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_firstChild}},lastChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastChild}},nextSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextSibling}},previousSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousSibling}},childNodes:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childNodes}},parentElement:{configurable:!0,enumerable:!0,
get:function(){return this.node.__shady_parentElement}},firstElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_firstElementChild}},lastElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastElementChild}},nextElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextElementSibling}},previousElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousElementSibling}},
children:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_children}},childElementCount:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childElementCount}},shadowRoot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_shadowRoot}},assignedSlot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_assignedSlot}},isConnected:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_isConnected}},innerHTML:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_innerHTML},set:function(a){this.node.__shady_innerHTML=a}},textContent:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_textContent},set:function(a){this.node.__shady_textContent=a}},slot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_slot},set:function(a){this.node.__shady_slot=a}},className:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_className},set:function(a){this.node.__shady_className=
a}}});function fd(a){Object.defineProperty(ed.prototype,a,{get:function(){return this.node["__shady_"+a]},set:function(b){this.node["__shady_"+a]=b},configurable:!0})}Lb.forEach(function(a){return fd(a)});Mb.forEach(function(a){return fd(a)});var gd=new WeakMap;function hd(a){if(y(a)||a instanceof ed)return a;var b=gd.get(a);b||(b=new ed(a),gd.set(a,b));return b};if(w.inUse){var id=w.j?function(a){return a}:function(a){hb(a);gb(a);return a};window.ShadyDOM={inUse:w.inUse,patch:id,isShadyRoot:y,enqueue:Ea,flush:Fa,flushInitial:function(a){a.Ab()},settings:w,filterMutations:Ka,observeChildren:Ia,unobserveChildren:Ja,deferConnectionCallbacks:w.deferConnectionCallbacks,preferPerformance:w.preferPerformance,handlesDynamicScoping:!0,wrap:w.noPatch?hd:id,wrapIfNeeded:w.noPatch===!0?hd:function(a){return a},Wrapper:ed,composedPath:qb,noPatch:w.noPatch,patchOnDemand:w.Da,
nativeMethods:Ta,nativeTree:Ua,patchElementProto:Sc,querySelectorImplementation:w.querySelectorImplementation};ab();Rc("__shady_");Object.defineProperty(document,"_activeElement",Lc.activeElement);A(Window.prototype,Oc,"__shady_");w.noPatch?w.Da&&A(Element.prototype,Cc):(Rc(),Kb());Fb();window.Event=Hb;window.CustomEvent=Ib;window.MouseEvent=Jb;window.ShadowRoot=Ac};/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at
 http://polymer.github.io/LICENSE.txt The complete set of authors may be found
 at http://polymer.github.io/AUTHORS.txt The complete set of contributors may
 be found at http://polymer.github.io/CONTRIBUTORS.txt Code distributed by
 Google as part of the polymer project is also subject to an additional IP
 rights grant found at http://polymer.github.io/PATENTS.txt
*/
var jd=window.Document.prototype.createElement,kd=window.Document.prototype.createElementNS,ld=window.Document.prototype.importNode,md=window.Document.prototype.prepend,nd=window.Document.prototype.append,od=window.DocumentFragment.prototype.prepend,pd=window.DocumentFragment.prototype.append,qd=window.Node.prototype.cloneNode,rd=window.Node.prototype.appendChild,sd=window.Node.prototype.insertBefore,td=window.Node.prototype.removeChild,ud=window.Node.prototype.replaceChild,vd=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),wd=window.Element.prototype.attachShadow,xd=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),yd=window.Element.prototype.getAttribute,zd=window.Element.prototype.setAttribute,Ad=window.Element.prototype.removeAttribute,Bd=window.Element.prototype.toggleAttribute,Cd=window.Element.prototype.getAttributeNS,Dd=window.Element.prototype.setAttributeNS,Ed=window.Element.prototype.removeAttributeNS,Fd=window.Element.prototype.insertAdjacentElement,Gd=window.Element.prototype.insertAdjacentHTML,
Hd=window.Element.prototype.prepend,Id=window.Element.prototype.append,Jd=window.Element.prototype.before,Kd=window.Element.prototype.after,Ld=window.Element.prototype.replaceWith,Md=window.Element.prototype.remove,Nd=window.HTMLElement,Od=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),Pd=window.HTMLElement.prototype.insertAdjacentElement,Qd=window.HTMLElement.prototype.insertAdjacentHTML;var Rd=function(){var a=new Set;"annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" ").forEach(function(b){return a.add(b)});return a}();function Sd(a){var b=Rd.has(a);a=/^[a-z][.0-9_a-z]*-[-.0-9_a-z]*$/.test(a);return!b&&a}var Td=document.contains?document.contains.bind(document):document.documentElement.contains.bind(document.documentElement);
function M(a){var b=a.isConnected;if(b!==void 0)return b;if(Td(a))return!0;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}function Ud(a){var b=a.children;if(b)return Array.prototype.slice.call(b);b=[];for(a=a.firstChild;a;a=a.nextSibling)a.nodeType===Node.ELEMENT_NODE&&b.push(a);return b}
function Vd(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}
function Wd(a,b,c){for(var e=a;e;){if(e.nodeType===Node.ELEMENT_NODE){var d=e;b(d);var f=d.localName;if(f==="link"&&d.getAttribute("rel")==="import"){e=d.import;c===void 0&&(c=new Set);if(e instanceof Node&&!c.has(e))for(c.add(e),e=e.firstChild;e;e=e.nextSibling)Wd(e,b,c);e=Vd(a,d);continue}else if(f==="template"){e=Vd(a,d);continue}if(d=d.__CE_shadowRoot)for(d=d.firstChild;d;d=d.nextSibling)Wd(d,b,c)}e=e.firstChild?e.firstChild:Vd(a,e)}};function Xd(){var a=!(N==null||!N.noDocumentConstructionObserver),b=!(N==null||!N.shadyDomFastWalk);this.T=[];this.va=[];this.L=!1;this.shadyDomFastWalk=b;this.Dc=!a}function Yd(a,b,c,e){var d=window.ShadyDOM;if(a.shadyDomFastWalk&&d&&d.inUse){if(b.nodeType===Node.ELEMENT_NODE&&c(b),b.querySelectorAll)for(a=d.nativeMethods.querySelectorAll.call(b,"*"),b=0;b<a.length;b++)c(a[b])}else Wd(b,c,e)}function Zd(a,b){a.L=!0;a.T.push(b)}function $d(a,b){a.L=!0;a.va.push(b)}
function ae(a,b){a.L&&Yd(a,b,function(c){return be(a,c)})}function be(a,b){if(a.L&&!b.__CE_patched){b.__CE_patched=!0;for(var c=0;c<a.T.length;c++)a.T[c](b);for(c=0;c<a.va.length;c++)a.va[c](b)}}function O(a,b){var c=[];Yd(a,b,function(d){return c.push(d)});for(b=0;b<c.length;b++){var e=c[b];e.__CE_state===1?a.connectedCallback(e):ce(a,e)}}function P(a,b){var c=[];Yd(a,b,function(d){return c.push(d)});for(b=0;b<c.length;b++){var e=c[b];e.__CE_state===1&&a.disconnectedCallback(e)}}
function Q(a,b,c){c=c===void 0?{}:c;var e=c.Ec,d=c.upgrade||function(g){return ce(a,g)},f=[];Yd(a,b,function(g){a.L&&be(a,g);if(g.localName==="link"&&g.getAttribute("rel")==="import"){var h=g.import;h instanceof Node&&(h.__CE_isImportDocument=!0,h.__CE_registry=document.__CE_registry);h&&h.readyState==="complete"?h.__CE_documentLoadHandled=!0:g.addEventListener("load",function(){var k=g.import;if(!k.__CE_documentLoadHandled){k.__CE_documentLoadHandled=!0;var l=new Set;e&&(e.forEach(function(n){return l.add(n)}),
l.delete(k));Q(a,k,{Ec:l,upgrade:d})}})}else f.push(g)},e);for(b=0;b<f.length;b++)d(f[b])}function ce(a,b){try{var c=a.Lb(b.ownerDocument,b.localName);c&&a.hc(b,c)}catch(e){de(e)}}m=Xd.prototype;
m.hc=function(a,b){if(a.__CE_state===void 0){b.constructionStack.push(a);try{try{if(new b.constructorFunction!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{b.constructionStack.pop()}}catch(f){throw a.__CE_state=2,f;}a.__CE_state=1;a.__CE_definition=b;if(b.attributeChangedCallback&&a.hasAttributes()){b=b.observedAttributes;for(var c=0;c<b.length;c++){var e=b[c],d=a.getAttribute(e);d!==null&&this.attributeChangedCallback(a,e,null,d,null)}}M(a)&&
this.connectedCallback(a)}};m.connectedCallback=function(a){var b=a.__CE_definition;if(b.connectedCallback)try{b.connectedCallback.call(a)}catch(c){de(c)}};m.disconnectedCallback=function(a){var b=a.__CE_definition;if(b.disconnectedCallback)try{b.disconnectedCallback.call(a)}catch(c){de(c)}};m.attributeChangedCallback=function(a,b,c,e,d){var f=a.__CE_definition;if(f.attributeChangedCallback&&f.observedAttributes.indexOf(b)>-1)try{f.attributeChangedCallback.call(a,b,c,e,d)}catch(g){de(g)}};
m.Lb=function(a,b){var c=a.__CE_registry;if(c&&(a.defaultView||a.__CE_isImportDocument))return ee(c,b)};
function fe(a,b,c,e){var d=b.__CE_registry;if(d&&(e===null||e==="http://www.w3.org/1999/xhtml")&&(d=ee(d,c)))try{var f=new d.constructorFunction;if(f.__CE_state===void 0||f.__CE_definition===void 0)throw Error("Failed to construct '"+c+"': The returned value was not constructed with the HTMLElement constructor.");if(f.namespaceURI!=="http://www.w3.org/1999/xhtml")throw Error("Failed to construct '"+c+"': The constructed element's namespace must be the HTML namespace.");if(f.hasAttributes())throw Error("Failed to construct '"+
c+"': The constructed element must not have any attributes.");if(f.firstChild!==null)throw Error("Failed to construct '"+c+"': The constructed element must not have any children.");if(f.parentNode!==null)throw Error("Failed to construct '"+c+"': The constructed element must not have a parent node.");if(f.ownerDocument!==b)throw Error("Failed to construct '"+c+"': The constructed element's owner document is incorrect.");if(f.localName!==c)throw Error("Failed to construct '"+c+"': The constructed element's local name is incorrect.");
return f}catch(g){return de(g),b=e===null?jd.call(b,c):kd.call(b,e,c),Object.setPrototypeOf(b,HTMLUnknownElement.prototype),b.__CE_state=2,b.__CE_definition=void 0,be(a,b),b}b=e===null?jd.call(b,c):kd.call(b,e,c);be(a,b);return b}
function de(a){var b="",c="",e=0,d=0;a instanceof Error?(b=a.message,c=a.sourceURL||a.fileName||"",e=a.line||a.lineNumber||0,d=a.column||a.columnNumber||0):b="Uncaught "+String(a);var f=void 0;ErrorEvent.prototype.initErrorEvent===void 0?f=new ErrorEvent("error",{cancelable:!0,message:b,filename:c,lineno:e,colno:d,error:a}):(f=document.createEvent("ErrorEvent"),f.initErrorEvent("error",!1,!0,b,c,e),f.preventDefault=function(){Object.defineProperty(this,"defaultPrevented",{configurable:!0,get:function(){return!0}})});
f.error===void 0&&Object.defineProperty(f,"error",{configurable:!0,enumerable:!0,get:function(){return a}});window.dispatchEvent(f);f.defaultPrevented||console.error(a)};function ge(){var a=this;this.bb=void 0;this.Ua=new Promise(function(b){a.Vb=b})}ge.prototype.resolve=function(a){if(this.bb)throw Error("Already resolved.");this.bb=a;this.Vb(a)};function he(a){var b=document;this.M=void 0;this.F=a;this.ca=b;Q(this.F,this.ca);this.ca.readyState==="loading"&&(this.M=new MutationObserver(this.Hb.bind(this)),this.M.observe(this.ca,{childList:!0,subtree:!0}))}he.prototype.disconnect=function(){this.M&&this.M.disconnect()};he.prototype.Hb=function(a){var b=this.ca.readyState;b!=="interactive"&&b!=="complete"||this.disconnect();for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,e=0;e<c.length;e++)Q(this.F,c[e])};function R(a){this.ea=new Map;this.fa=new Map;this.Ia=new Map;this.sa=!1;this.Aa=new Map;this.da=function(b){return b()};this.K=!1;this.ja=[];this.F=a;this.Ka=a.Dc?new he(a):void 0}m=R.prototype;m.uc=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructor getters must be functions.");ie(this,a);this.ea.set(a,b);this.ja.push(a);this.K||(this.K=!0,this.da(function(){return c.Ma()}))};
m.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");ie(this,a);je(this,a,b);this.ja.push(a);this.K||(this.K=!0,this.da(function(){return c.Ma()}))};
function ie(a,b){if(!Sd(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(ee(a,b)&&!window.enableHotReplacement)throw Error("A custom element with name '"+(b+"' has already been defined."));if(a.sa)throw Error("A custom element is already being defined.");}
function je(a,b,c){a.sa=!0;var e;try{var d=c.prototype;if(!(d instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=function(n){var t=d[n];if(t!==void 0&&!(t instanceof Function))throw Error("The '"+n+"' callback must be a function.");return t};var g=f("connectedCallback");var h=f("disconnectedCallback");var k=f("adoptedCallback");var l=(e=f("attributeChangedCallback"))&&c.observedAttributes||[]}catch(n){throw n;}finally{a.sa=!1}c={localName:b,
constructorFunction:c,connectedCallback:g,disconnectedCallback:h,adoptedCallback:k,attributeChangedCallback:e,observedAttributes:l,constructionStack:[]};a.fa.set(b,c);a.Ia.set(c.constructorFunction,c);return c}m.upgrade=function(a){Q(this.F,a)};
m.Ma=function(){var a=this;if(this.K!==!1){this.K=!1;for(var b=[],c=this.ja,e=new Map,d=0;d<c.length;d++)e.set(c[d],[]);Q(this.F,document,{upgrade:function(k){if(k.__CE_state===void 0){var l=k.localName,n=e.get(l);n?n.push(k):a.fa.has(l)&&b.push(k)}}});for(d=0;d<b.length;d++)ce(this.F,b[d]);for(d=0;d<c.length;d++){for(var f=c[d],g=e.get(f),h=0;h<g.length;h++)ce(this.F,g[h]);(f=this.Aa.get(f))&&f.resolve(void 0)}c.length=0}};m.get=function(a){if(a=ee(this,a))return a.constructorFunction};
m.whenDefined=function(a){if(!Sd(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.Aa.get(a);if(b)return b.Ua;b=new ge;this.Aa.set(a,b);var c=this.fa.has(a)||this.ea.has(a);a=this.ja.indexOf(a)===-1;c&&a&&b.resolve(void 0);return b.Ua};m.polyfillWrapFlushCallback=function(a){this.Ka&&this.Ka.disconnect();var b=this.da;this.da=function(c){return a(function(){return b(c)})}};
function ee(a,b){var c=a.fa.get(b);if(c)return c;if(c=a.ea.get(b)){a.ea.delete(b);try{return je(a,b,c())}catch(e){de(e)}}}R.prototype.define=R.prototype.define;R.prototype.upgrade=R.prototype.upgrade;R.prototype.get=R.prototype.get;R.prototype.whenDefined=R.prototype.whenDefined;R.prototype.polyfillDefineLazy=R.prototype.uc;R.prototype.polyfillWrapFlushCallback=R.prototype.polyfillWrapFlushCallback;function ke(a,b,c){function e(d){return function(){for(var f=r.apply(0,arguments),g=[],h=[],k=0;k<f.length;k++){var l=f[k];l instanceof Element&&M(l)&&h.push(l);if(l instanceof DocumentFragment)for(l=l.firstChild;l;l=l.nextSibling)g.push(l);else g.push(l)}d.apply(this,f);for(f=0;f<h.length;f++)P(a,h[f]);if(M(this))for(h=0;h<g.length;h++)f=g[h],f instanceof Element&&O(a,f)}}c.prepend!==void 0&&(b.prepend=e(c.prepend));c.append!==void 0&&(b.append=e(c.append))};function le(a){Document.prototype.createElement=function(b){return fe(a,this,b,null)};Document.prototype.importNode=function(b,c){b=ld.call(this,b,!!c);this.__CE_registry?Q(a,b):ae(a,b);return b};Document.prototype.createElementNS=function(b,c){return fe(a,this,c,b)};ke(a,Document.prototype,{prepend:md,append:nd})};function me(a){function b(e){return function(){for(var d=r.apply(0,arguments),f=[],g=[],h=0;h<d.length;h++){var k=d[h];k instanceof Element&&M(k)&&g.push(k);if(k instanceof DocumentFragment)for(k=k.firstChild;k;k=k.nextSibling)f.push(k);else f.push(k)}e.apply(this,d);for(d=0;d<g.length;d++)P(a,g[d]);if(M(this))for(g=0;g<f.length;g++)d=f[g],d instanceof Element&&O(a,d)}}var c=Element.prototype;Jd!==void 0&&(c.before=b(Jd));Kd!==void 0&&(c.after=b(Kd));Ld!==void 0&&(c.replaceWith=function(){for(var e=
r.apply(0,arguments),d=[],f=[],g=0;g<e.length;g++){var h=e[g];h instanceof Element&&M(h)&&f.push(h);if(h instanceof DocumentFragment)for(h=h.firstChild;h;h=h.nextSibling)d.push(h);else d.push(h)}g=M(this);Ld.apply(this,e);for(e=0;e<f.length;e++)P(a,f[e]);if(g)for(P(a,this),f=0;f<d.length;f++)e=d[f],e instanceof Element&&O(a,e)});Md!==void 0&&(c.remove=function(){var e=M(this);Md.call(this);e&&P(a,this)})};function ne(a){function b(d,f){Object.defineProperty(d,"innerHTML",{enumerable:f.enumerable,configurable:!0,get:f.get,set:function(g){var h=this,k=void 0;M(this)&&(k=[],Yd(a,this,function(t){t!==h&&k.push(t)}));f.set.call(this,g);if(k)for(var l=0;l<k.length;l++){var n=k[l];n.__CE_state===1&&a.disconnectedCallback(n)}this.ownerDocument.__CE_registry?Q(a,this):ae(a,this);return g}})}function c(d,f){d.insertAdjacentElement=function(g,h){var k=M(h);g=f.call(this,g,h);k&&P(a,h);M(g)&&O(a,h);return g}}
function e(d,f){function g(h,k){for(var l=[];h!==k;h=h.nextSibling)l.push(h);for(k=0;k<l.length;k++)Q(a,l[k])}d.insertAdjacentHTML=function(h,k){h=h.toLowerCase();if(h==="beforebegin"){var l=this.previousSibling;f.call(this,h,k);g(l||this.parentNode.firstChild,this)}else if(h==="afterbegin")l=this.firstChild,f.call(this,h,k),g(this.firstChild,l);else if(h==="beforeend")l=this.lastChild,f.call(this,h,k),g(l||this.firstChild,null);else if(h==="afterend")l=this.nextSibling,f.call(this,h,k),g(this.nextSibling,
l);else throw new SyntaxError("The value provided ("+String(h)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");}}wd&&(Element.prototype.attachShadow=function(d){d=wd.call(this,d);if(a.L&&!d.__CE_patched){d.__CE_patched=!0;for(var f=0;f<a.T.length;f++)a.T[f](d)}return this.__CE_shadowRoot=d});xd&&xd.get?b(Element.prototype,xd):Od&&Od.get?b(HTMLElement.prototype,Od):$d(a,function(d){b(d,{enumerable:!0,configurable:!0,get:function(){return qd.call(this,!0).innerHTML},set:function(f){var g=
this.localName==="template",h=g?this.content:this,k=kd.call(document,this.namespaceURI,this.localName);for(k.innerHTML=f;h.childNodes.length>0;)td.call(h,h.childNodes[0]);for(f=g?k.content:k;f.childNodes.length>0;)rd.call(h,f.childNodes[0])}})});Element.prototype.setAttribute=function(d,f){if(this.__CE_state!==1)return zd.call(this,d,f);var g=yd.call(this,d);zd.call(this,d,f);f=yd.call(this,d);a.attributeChangedCallback(this,d,g,f,null)};Element.prototype.setAttributeNS=function(d,f,g){if(this.__CE_state!==
1)return Dd.call(this,d,f,g);var h=Cd.call(this,d,f);Dd.call(this,d,f,g);g=Cd.call(this,d,f);a.attributeChangedCallback(this,f,h,g,d)};Element.prototype.removeAttribute=function(d){if(this.__CE_state!==1)return Ad.call(this,d);var f=yd.call(this,d);Ad.call(this,d);f!==null&&a.attributeChangedCallback(this,d,f,null,null)};Bd&&(Element.prototype.toggleAttribute=function(d,f){if(this.__CE_state!==1)return Bd.call(this,d,f);var g=yd.call(this,d),h=g!==null;f=Bd.call(this,d,f);if(h!==f){var k;a==null||
(k=a.attributeChangedCallback)==null||k.call(a,this,d,g,f?"":null,null)}return f});Element.prototype.removeAttributeNS=function(d,f){if(this.__CE_state!==1)return Ed.call(this,d,f);var g=Cd.call(this,d,f);Ed.call(this,d,f);var h=Cd.call(this,d,f);g!==h&&a.attributeChangedCallback(this,f,g,h,d)};Pd?c(HTMLElement.prototype,Pd):Fd&&c(Element.prototype,Fd);Qd?e(HTMLElement.prototype,Qd):Gd&&e(Element.prototype,Gd);ke(a,Element.prototype,{prepend:Hd,append:Id});me(a)};var oe={};function pe(a){function b(){var c=this.constructor;var e=document.__CE_registry.Ia.get(c);if(!e)throw Error("Failed to construct a custom element: The constructor was not registered with `customElements`.");var d=e.constructionStack;if(d.length===0)return d=jd.call(document,e.localName),Object.setPrototypeOf(d,c.prototype),d.__CE_state=1,d.__CE_definition=e,be(a,d),d;var f=d.length-1,g=d[f];if(g===oe)throw Error("Failed to construct '"+e.localName+"': This element was already constructed.");d[f]=
oe;Object.setPrototypeOf(g,c.prototype);be(a,g);return g}b.prototype=Nd.prototype;Object.defineProperty(HTMLElement.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:b});window.HTMLElement=b};function qe(a){function b(c,e){Object.defineProperty(c,"textContent",{enumerable:e.enumerable,configurable:!0,get:e.get,set:function(d){if(this.nodeType===Node.TEXT_NODE)e.set.call(this,d);else{var f=void 0;if(this.firstChild){var g=this.childNodes,h=g.length;if(h>0&&M(this)){f=Array(h);for(var k=0;k<h;k++)f[k]=g[k]}}e.set.call(this,d);if(f)for(d=0;d<f.length;d++)P(a,f[d])}}})}Node.prototype.insertBefore=function(c,e){if(c instanceof DocumentFragment){var d=Ud(c);c=sd.call(this,c,e);if(M(this))for(e=
0;e<d.length;e++)O(a,d[e]);return c}d=c instanceof Element&&M(c);e=sd.call(this,c,e);d&&P(a,c);M(this)&&O(a,c);return e};Node.prototype.appendChild=function(c){if(c instanceof DocumentFragment){var e=Ud(c);c=rd.call(this,c);if(M(this))for(var d=0;d<e.length;d++)O(a,e[d]);return c}e=c instanceof Element&&M(c);d=rd.call(this,c);e&&P(a,c);M(this)&&O(a,c);return d};Node.prototype.cloneNode=function(c){c=qd.call(this,!!c);this.ownerDocument.__CE_registry?Q(a,c):ae(a,c);return c};Node.prototype.removeChild=
function(c){var e=c instanceof Element&&M(c),d=td.call(this,c);e&&P(a,c);return d};Node.prototype.replaceChild=function(c,e){if(c instanceof DocumentFragment){var d=Ud(c);c=ud.call(this,c,e);if(M(this))for(P(a,e),e=0;e<d.length;e++)O(a,d[e]);return c}d=c instanceof Element&&M(c);var f=ud.call(this,c,e),g=M(this);g&&P(a,e);d&&P(a,c);g&&O(a,c);return f};vd&&vd.get?b(Node.prototype,vd):Zd(a,function(c){b(c,{enumerable:!0,configurable:!0,get:function(){for(var e=[],d=this.firstChild;d;d=d.nextSibling)d.nodeType!==
Node.COMMENT_NODE&&e.push(d.textContent);return e.join("")},set:function(e){for(;this.firstChild;)td.call(this,this.firstChild);e!=null&&e!==""&&rd.call(this,document.createTextNode(e))}})})};var N=window.customElements;function re(){var a=new Xd;pe(a);le(a);ke(a,DocumentFragment.prototype,{prepend:od,append:pd});qe(a);ne(a);window.CustomElementRegistry=R;a=new R(a);document.__CE_registry=a;Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:a})}N&&!N.forcePolyfill&&typeof N.define=="function"&&typeof N.get=="function"||re();window.__CE_installPolyfill=re;/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function se(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function te(a){var b=a=a.replace(ue,"").replace(ve,""),c=new se;c.start=0;c.end=b.length;for(var e=c,d=0,f=b.length;d<f;d++)if(b[d]==="{"){e.rules||(e.rules=[]);var g=e,h=g.rules[g.rules.length-1]||null;e=new se;e.start=d+1;e.parent=g;e.previous=h;g.rules.push(e)}else b[d]==="}"&&(e.end=d+1,e=e.parent||c);return we(c,a)}
function we(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=_expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(c),c=c.replace(xe," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=c.indexOf("@")===0,a.atRule?c.indexOf("@media")===0?a.type=4:c.match(ye)&&(a.type=7,a.keyframesName=a.selector.split(xe).pop()):a.type=c.indexOf("--")===
0?1E3:1);if(c=a.rules)for(var e=0,d=c.length,f=void 0;e<d&&(f=c[e]);e++)we(f,b);return a}function _expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(){for(var b=arguments[1],c=6-b.length;c--;)b="0"+b;return"\\"+b})}
function ze(a,b,c){c=c===void 0?"":c;var e="";if(a.cssText||a.rules){var d=a.rules;if(d&&!_hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(d))for(var f=0,g=d.length,h=void 0;f<g&&(h=d[f]);f++)e=ze(h,b,e);else b?b=a.cssText:(b=a.cssText,b=b.replace(Ae,"").replace(Be,""),b=b.replace(Ce,"").replace(De,"")),(e=b.trim())&&(e="  "+e+"\n")}e&&(a.selector&&(c+=a.selector+" {\n"),c+=e,a.selector&&(c+="}\n\n"));return c}
function _hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){a=a[0];return!!a&&!!a.selector&&a.selector.indexOf("--")===0}var ue=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,ve=/@import[^;]*;/gim,Ae=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Be=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Ce=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,De=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,ye=/^@[^\s]*keyframes/,xe=/\s+/g;var S=!(window.ShadyDOM&&window.ShadyDOM.inUse),Ee;function Fe(a){Ee=a&&a.shimcssproperties?!1:S||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var Ge;window.ShadyCSS&&window.ShadyCSS.cssBuild!==void 0&&(Ge=window.ShadyCSS.cssBuild);var He=!(!window.ShadyCSS||!window.ShadyCSS.disableRuntime);
window.ShadyCSS&&window.ShadyCSS.nativeCss!==void 0?Ee=window.ShadyCSS.nativeCss:window.ShadyCSS?(Fe(window.ShadyCSS),window.ShadyCSS=void 0):Fe(window.WebComponents&&window.WebComponents.flags);var T=Ee;var Ie=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,Je=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,Ke=/(--[\w-]+)\s*([:,;)]|$)/gi,Le=/(animation\s*:)|(animation-name\s*:)/,Me=/@media\s(.*)/,Ne=/\{[^}]*\}/g;var Oe=new Set;function Pe(a,b){if(!a)return"";typeof a==="string"&&(a=te(a));b&&Qe(a,b);return ze(a,T)}function Re(a){!a.__cssRules&&a.textContent&&(a.__cssRules=te(a.textContent));return a.__cssRules||null}function Se(a){return!!a.parent&&a.parent.type===7}function Qe(a,b,c,e){if(a){var d=!1,f=a.type;if(e&&f===4){var g=a.selector.match(Me);g&&(window.matchMedia(g[1]).matches||(d=!0))}f===1?b(a):c&&f===7?c(a):f===1E3&&(d=!0);if((a=a.rules)&&!d)for(d=0,f=a.length,g=void 0;d<f&&(g=a[d]);d++)Qe(g,b,c,e)}}
function Te(a,b,c,e){var d=document.createElement("style");b&&d.setAttribute("scope",b);d.textContent=a;if(window.enableHotReplacement&&(a=document.head.querySelector("style[scope="+b+"]")))return a.parentElement.replaceChild(d,a),d;Ue(d,c,e);return d}var U=null;function Ve(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(U?U.nextSibling:null)||b.firstChild);return U=a}
function Ue(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);U?a.compareDocumentPosition(U)===Node.DOCUMENT_POSITION_PRECEDING&&(U=a):U=a}function We(a,b){for(var c=0,e=a.length;b<e;b++)if(a[b]==="(")c++;else if(a[b]===")"&&--c===0)return b;return-1}
function Xe(a,b){var c=a.indexOf("var(");if(c===-1)return b(a,"","","");var e=We(a,c+3),d=a.substring(c+4,e);c=a.substring(0,c);a=Xe(a.substring(e+1),b);e=d.indexOf(",");return e===-1?b(c,d.trim(),"",a):b(c,d.substring(0,e).trim(),d.substring(e+1).trim(),a)}function Ye(a,b){S?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}var Ze=window.ShadyDOM&&window.ShadyDOM.wrap||function(a){return a};
function V(a){var b=a.localName,c="";b?b.indexOf("-")>-1||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,Z:c}}function $e(a){for(var b=[],c="",e=0;e>=0&&e<a.length;e++)if(a[e]==="("){var d=We(a,e);c+=a.slice(e,d+1);e=d}else a[e]===","?(b.push(c),c=""):c+=a[e];c&&b.push(c);return b}
function af(a){if(Ge!==void 0)return Ge;if(a.__cssBuild===void 0){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b=a.localName==="template"?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),b[0]==="css-build")){b=b[1];break a}b=""}if(b!==""){var c=a.localName==="template"?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function bf(a){a=a===void 0?"":a;return a!==""&&T?S?a==="shadow":a==="shady":!1};function cf(a,b){var c=window.shadyCSSStyleTransformHooks;return c&&(c=c.didTransformSelector,typeof c==="function")?c(a,b):a}function df(){}function ef(a,b){var c=W;c.ia(a,function(e){c.element(e,b||"")})}m=df.prototype;m.ia=function(a,b){a.nodeType===Node.ELEMENT_NODE&&b(a);if(a=a.localName==="template"?(a.content||a._content||a).childNodes:a.children||a.childNodes)for(var c=0;c<a.length;c++)this.ia(a[c],b)};
m.element=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var e=a.getAttribute("class");c?e&&(b=e.replace("style-scope","").replace(b,""),Ye(a,b)):Ye(a,(e?e+" ":"")+"style-scope "+b)}};function ff(a,b,c){var e=W;e.ia(a,function(d){e.element(d,b,!0);e.element(d,c)})}function gf(a,b){var c=W;c.ia(a,function(e){c.element(e,b||"",!0)})}
function hf(a,b,c,e,d){var f=W;d=d===void 0?"":d;d===""&&(S||(e===void 0?"":e)==="shady"?d=Pe(b,c):(a=V(a),d=jf(f,b,a.is,a.Z,c)+"\n\n"));return d.trim()}function jf(a,b,c,e,d){var f=a.ra(c,e);c=a.Ha(c);return Pe(b,function(g){g.sc||(a.Xa(g,a.ya,c,f),g.sc=!0);d&&d(g,c,f)})}m.Ha=function(a){return a?"."+a:""};m.ra=function(a,b){return b?"[is="+a+"]":a};m.Xa=function(a,b,c,e){a.selector=a.o=this.Ya(a,b,c,e)};
m.Ya=function(a,b,c,e){var d=$e(a.selector);if(!Se(a)){a=0;for(var f=d.length,g=void 0;a<f&&(g=d[a]);a++)d[a]=b.call(this,g,c,e)}return d.filter(function(h){return!!h}).join(",")};m.ab=function(a){return a.replace(kf,function(b,c,e){e.indexOf("+")>-1?e=e.replace(/\+/g,"___"):e.indexOf("___")>-1&&(e=e.replace(/___/g,"+"));return":"+c+"("+e+")"})};
m.Qb=function(a){for(var b=[],c;c=a.match(lf);){var e=c.index,d=We(a,e);if(d===-1)throw Error(c.input+" selector missing ')'");c=a.slice(e,d+1);a=a.replace(c,"\ue000");b.push(c)}return{Ea:a,matches:b}};m.Ub=function(a,b){var c=a.split("\ue000");return b.reduce(function(e,d,f){return e+d+c[f+1]},c[0])};
m.ya=function(a,b,c){var e=this,d=!1;a=a.trim();var f=kf.test(a);f&&(a=a.replace(kf,function(k,l,n){return":"+l+"("+n.replace(/\s/g,"")+")"}),a=this.ab(a));var g=lf.test(a);if(g){var h=this.Qb(a);a=h.Ea;h=h.matches}a=a.replace(mf,":host $1");a=a.replace(nf,function(k,l,n){d||(k=e.bc(n,l,b,c),d=d||k.stop,l=k.kc,n=k.value);return l+n});g&&(a=this.Ub(a,h));f&&(a=this.ab(a));a=a.replace(of,function(k,l,n,t){return'[dir="'+n+'"] '+l+t+", "+l+'[dir="'+n+'"]'+t});return cf(a,b)};
m.bc=function(a,b,c,e){var d=a.indexOf("::slotted");a.indexOf(":host")>=0?a=this.dc(a,e):d!==0&&(a=c?this.Za(a,c):a);c=!1;d>=0&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(pf,function(g,h){return" > "+h}))}return{value:a,kc:b,stop:f}};m.Za=function(a,b){a=a.split(/(\[.+?\])/);for(var c=[],e=0;e<a.length;e++)if(e%2===1)c.push(a[e]);else{var d=a[e];if(d!==""||e!==a.length-1)d=d.split(":"),d[0]+=b,c.push(d.join(":"))}return c.join("")};
m.dc=function(a,b){var c=a.match(qf);return(c=c&&c[2].trim()||"")?c[0].match(rf)?a.replace(qf,function(e,d,f){return b+f}):c.split(rf)[0]===b?c:"should_not_match":a.replace(":host",b)};function sf(a){a.selector===":root"&&(a.selector="html")}m.cc=function(a){return a.match(":host")?"":a.match("::slotted")?this.ya(a,":not(.style-scope)"):cf(this.Za(a.trim(),":not(.style-scope)"),":not(.style-scope)")};ca.Object.defineProperties(df.prototype,{aa:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var kf=/:(nth[-\w]+)\(([^)]+)\)/,nf=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,rf=/[[.:#*]/,mf=RegExp("^(::slotted)"),qf=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,pf=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,of=/(.*):dir\((?:(ltr|rtl))\)(.*)/,lf=/:(?:matches|any|-(?:webkit|moz)-any)/,W=new df;function tf(a,b,c,e,d){this.A=a||null;this.placeholder=b||null;this.Ca=c||[];this.R=null;this.cssBuild=d||"";this.Z=e||"";this.O=this.v=this.D=null}function X(a){return a?a.__styleInfo:null}function uf(a,b){return a.__styleInfo=b}tf.prototype.Gb=function(){return this.A};tf.prototype._getStyleRules=tf.prototype.Gb;function vf(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var wf=/:host\s*>\s*/,xf=navigator.userAgent.match("Trident");function yf(){}function zf(a){var b={},c=[],e=0;Qe(a,function(f){Af(f);f.index=e++;f=f.l.cssText;for(var g;g=Ke.exec(f);){var h=g[1];g[2]!==":"&&(b[h]=!0)}},function(f){c.push(f)});a.Jb=c;a=[];for(var d in b)a.push(d);return a}
function Af(a){if(!a.l){var b={},c={};Bf(a,c)&&(b.C=c,a.rules=null);b.cssText=a.parsedCssText.replace(Ne,"").replace(Ie,"");a.l=b}}function Bf(a,b){var c=a.l;if(c){if(c.C)return Object.assign(b,c.C),!0}else{c=a.parsedCssText;for(var e;a=Ie.exec(c);){e=(a[2]||a[3]).trim();if(e!=="inherit"||e!=="unset")b[a[1].trim()]=e;e=!0}return e}}
function Cf(a,b,c){b&&(b=b.indexOf(";")>=0?Df(a,b,c):Xe(b,function(e,d,f,g){if(!d)return e+g;(d=Cf(a,c[d],c))&&d!=="initial"?d==="apply-shim-inherit"&&(d="inherit"):d=Cf(a,c[f]||f,c)||f;return e+(d||"")+g}));return b&&b.trim()||""}
function Df(a,b,c){b=b.split(";");for(var e=0,d,f;e<b.length;e++)if(d=b[e]){Je.lastIndex=0;if(f=Je.exec(d))d=Cf(a,c[f[1]],c);else if(f=d.indexOf(":"),f!==-1){var g=d.substring(f);g=g.trim();g=Cf(a,g,c)||g;d=d.substring(0,f)+g}b[e]=d&&d.lastIndexOf(";")===d.length-1?d.slice(0,-1):d||""}return b.join(";")}
function Ef(a,b){var c={},e=[];Qe(a,function(d){d.l||Af(d);var f=d.o||d.parsedSelector;b&&d.l.C&&f&&vf.call(b,f)&&(Bf(d,c),d=d.index,f=parseInt(d/32,10),e[f]=(e[f]||0)|1<<d%32)},null,!0);return{C:c,key:e}}
function Ff(a,b,c,e){b.l||Af(b);if(b.l.C){var d=V(a);a=d.is;d=d.Z;d=a?W.ra(a,d):"html";var f=b.parsedSelector;var g=!!f.match(wf)||d==="html"&&f.indexOf("html")>-1;var h=f.indexOf(":host")===0&&!g;c==="shady"&&(g=f===d+" > *."+d||f.indexOf("html")!==-1,h=!g&&f.indexOf(d)===0);if(g||h)c=d,h&&(b.o||(b.o=W.Ya(b,W.ya,W.Ha(a),d)),c=b.o||d),g&&d==="html"&&(c=b.o||b.Hc),e({Ea:c,rc:h,Gc:g})}}
function Gf(a,b,c){var e={},d={};Qe(b,function(f){Ff(a,f,c,function(g){vf.call(a._element||a,g.Ea)&&(g.rc?Bf(f,e):Bf(f,d))})},null,!0);return{wc:d,qc:e}}
function Hf(a,b,c,e){var d=V(b),f=W.ra(d.is,d.Z),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),h=X(b);d=h.A;h=h.cssBuild;var k=a.wb(b,d,e);return hf(b,d,function(l){var n="";l.l||Af(l);l.l.cssText&&(n=Df(a,l.l.cssText,c));l.cssText=n;if(!S&&!Se(l)&&l.cssText){var t=n=l.cssText;l.eb==null&&(l.eb=Le.test(n));if(l.eb)if(l.na==null){l.na=[];for(var C in k)t=k[C],t=t(n),n!==t&&(n=t,l.na.push(C))}else{for(C=0;C<l.na.length;++C)t=k[l.na[C]],n=t(n);t=n}l.cssText=t;
a.Zb(l,g,f,e)}},h)}yf.prototype.wb=function(a,b,c){a=b.Jb;b={};if(!S&&a)for(var e=0,d=a[e];e<a.length;d=a[++e])this.Yb(d,c),b[d.keyframesName]=this.Kb(d);return b};yf.prototype.Kb=function(a){return function(b){return b.replace(a.tc,a.ib)}};yf.prototype.Yb=function(a,b){a.tc=new RegExp("\\b"+a.keyframesName+"(?!\\B|-)","g");a.ib=a.keyframesName+"-"+b;a.o=a.o||a.selector;a.selector=a.o.replace(a.keyframesName,a.ib)};
yf.prototype.Zb=function(a,b,c,e){a.o=a.o||a.selector;e="."+e;for(var d=$e(a.o),f=0,g=d.length,h=void 0;f<g&&(h=d[f]);f++)d[f]=h.match(b)?h.replace(c,e):e+" "+h;a.selector=d.join(",")};function If(a,b){var c=Jf,e=Re(a);a.textContent=Pe(e,function(d){var f=d.cssText=d.parsedCssText;d.l&&d.l.cssText&&(f=f.replace(Ae,"").replace(Be,""),d.cssText=Df(c,f,b))})}ca.Object.defineProperties(yf.prototype,{kb:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Jf=new yf;var Kf={},Lf=window.customElements;if(Lf&&!S&&!He){var Mf=Lf.define;Lf.define=function(a,b,c){Kf[a]||(Kf[a]=Ve(a));Mf.call(Lf,a,b,c)}};function Nf(){this.cache={};this.Bc=100}Nf.prototype.jc=function(a,b,c){for(var e=0;e<c.length;e++){var d=c[e];if(a.C[d]!==b[d])return!1}return!0};Nf.prototype.store=function(a,b,c,e){var d=this.cache[a]||[];d.push({C:b,styleElement:c,v:e});d.length>this.Bc&&d.shift();this.cache[a]=d};Nf.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var e=a.length-1;e>=0;e--){var d=a[e];if(this.jc(d,b,c))return d}};function Of(){}var Pf=new RegExp(W.aa+"\\s*([^\\s]*)");function Qf(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(Pf))?a[1]:""}function Rf(a){var b=Ze(a).getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?V(a).is:""}
function Sf(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var e=0;e<c.addedNodes.length;e++){var d=c.addedNodes[e];if(d.nodeType===Node.ELEMENT_NODE){var f=d.getRootNode(),g=Qf(d);if(g&&f===d.ownerDocument&&(d.localName!=="style"&&d.localName!=="template"||af(d)===""))gf(d,g);else if(f instanceof ShadowRoot)for(f=Rf(d),f!==g&&ff(d,g,f),d=window.ShadyDOM.nativeMethods.querySelectorAll.call(d,":not(."+W.aa+")"),g=0;g<d.length;g++){f=d[g];
var h=Rf(f);h&&W.element(f,h)}}}}}
if(!(S||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var Tf=new MutationObserver(Sf),Uf=function(a){Tf.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Uf(document);else{var Vf=function(){Uf(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Vf):requestAnimationFrame(function(){if(document.readyState==="loading"){var a=function(){Vf();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else Vf()})}Of=function(){Sf(Tf.takeRecords())}};var Wf={};var Xf=Promise.resolve();function Yf(a){if(a=Wf[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Zf(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function $f(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,Xf.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var ag={},bg=new Nf;function Y(){this.Va={};this.J=document.documentElement;var a=new se;a.rules=[];this.B=uf(this.J,new tf(a));this.ta=!1;this.h=this.m=null}m=Y.prototype;m.flush=function(){Of()};m.Cb=function(a){var b=this.Va[a]=(this.Va[a]||0)+1;return a+"-"+b};m.nc=function(a){return Re(a)};m.Ac=function(a){return Pe(a)};
m.Bb=function(a){var b=[];a=a.content.querySelectorAll("style");for(var c=0;c<a.length;c++){var e=a[c];if(e.hasAttribute("shady-unscoped")){if(!S){var d=e.textContent;if(!Oe.has(d)){Oe.add(d);var f=document.createElement("style");f.setAttribute("shady-unscoped","");f.textContent=d;document.head.appendChild(f)}e.parentNode.removeChild(e)}}else b.push(e.textContent),e.parentNode.removeChild(e)}return b.join("").trim()};
m.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
m.prepareTemplateStyles=function(a,b,c){if(!a._prepared&&!He){S||Kf[b]||(Kf[b]=Ve(b));a._prepared=!0;a.name=b;a.extends=c;Wf[b]=a;var e=af(a),d=bf(e);c={is:b,extends:c};var f=this.Bb(a)+(ag[b]||"");this.S();if(!d){var g;if(g=!e)g=Je.test(f)||Ie.test(f),Je.lastIndex=0,Ie.lastIndex=0;var h=te(f);g&&T&&this.m&&this.m.transformRules(h,b);a._styleAst=h}g=[];T||(g=zf(a._styleAst));if(!g.length||T)b=this.Db(c,a._styleAst,S?a.content:null,Kf[b]||null,e,d?f:""),a._style=b;a.Pb=g}};
m.prepareAdoptedCssText=function(a,b){ag[b]=a.join(" ")};m.prepareTemplateDom=function(a,b){if(!He){var c=af(a);S||c==="shady"||a._domPrepared||(a._domPrepared=!0,ef(a.content,b))}};m.Db=function(a,b,c,e,d,f){f=hf(a,b,null,d,f);return f.length?Te(f,a.is,c,e):null};m.Sa=function(a){var b=V(a),c=b.is;b=b.Z;var e=Kf[c]||null,d=Wf[c];if(d){c=d._styleAst;var f=d.Pb;d=af(d);b=new tf(c,e,f,b,d);uf(a,b);return b}};
m.xb=function(){return!this.m&&window.ShadyCSS&&window.ShadyCSS.ApplyShim?(this.m=window.ShadyCSS.ApplyShim,this.m.invalidCallback=Yf,!0):!1};m.yb=function(){var a=this;!this.h&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(this.h=window.ShadyCSS.CustomStyleInterface,this.h.transformCallback=function(b){a.hb(b)},this.h.validateCallback=function(){requestAnimationFrame(function(){(a.h.enqueued||a.ta)&&a.flushCustomStyles()})})};m.S=function(){var a=this.xb();this.yb();return a};
m.flushCustomStyles=function(){if(!He){var a=this.S();if(this.h){var b=this.h.processStyles();!a&&!this.h.enqueued||bf(this.B.cssBuild)||(T?this.B.cssBuild||this.Xb(b):(this.Tb(b),this.za(this.J,this.B),this.ob(b),this.ta&&this.styleDocument()),this.h.enqueued=!1)}}};
m.Tb=function(a){var b=this;a=a.map(function(c){return b.h.getStyleForCustomStyle(c)}).filter(function(c){return!!c});a.sort(function(c,e){c=e.compareDocumentPosition(c);return c&Node.DOCUMENT_POSITION_FOLLOWING?1:c&Node.DOCUMENT_POSITION_PRECEDING?-1:0});this.B.A.rules=a.map(function(c){return Re(c)})};
m.styleElement=function(a,b){if(He){if(b){X(a)||uf(a,new tf(null));var c=X(a);this.Qa(c,b);cg(this,a,c)}}else if(c=X(a)||this.Sa(a))this.ua(a)||(this.ta=!0),b&&this.Qa(c,b),T?cg(this,a,c):(this.flush(),this.za(a,c),c.Ca&&c.Ca.length&&this.pb(a,c))};m.Qa=function(a,b){a.R=a.R||{};Object.assign(a.R,b)};
function cg(a,b,c){var e=V(b).is;if(c.R){var d=c.R,f;for(f in d)f===null?b.style.removeProperty(f):b.style.setProperty(f,d[f])}if(((d=Wf[e])||a.ua(b))&&(!d||af(d)==="")&&d&&d._style&&!Zf(d)){if(Zf(d)||d._applyShimValidatingVersion!==d._applyShimNextVersion)a.S(),a.m&&a.m.transformRules(d._styleAst,e),d._style.textContent=hf(b,c.A),$f(d);S&&(a=b.shadowRoot)&&(a=a.querySelector("style"))&&(a.textContent=hf(b,c.A));c.A=d._styleAst}}
m.xa=function(a){return(a=Ze(a).getRootNode().host)?X(a)||this.Sa(a)?a:this.xa(a):this.J};m.ua=function(a){return a===this.J};
m.pb=function(a,b){var c=V(a).is,e=bg.fetch(c,b.D,b.Ca),d=e?e.styleElement:null,f=b.v;b.v=e&&e.v||this.Cb(c);var g=b.D;var h=b.v;var k=Jf;g=d?d.textContent||"":Hf(k,a,g,h);k=X(a);var l=k.O;l&&!S&&l!==d&&(l._useCount--,l._useCount<=0&&l.parentNode&&l.parentNode.removeChild(l));S?k.O?(k.O.textContent=g,d=k.O):g&&(d=Te(g,h,a.shadowRoot,k.placeholder)):d?d.parentNode||(xf&&g.indexOf("@media")>-1&&(d.textContent=g),Ue(d,null,k.placeholder)):g&&(d=Te(g,h,null,k.placeholder));d&&(d._useCount=d._useCount||
0,k.O!=d&&d._useCount++,k.O=d);h=d;S||(d=b.v,k=g=a.getAttribute("class")||"",f&&(k=g.replace(new RegExp("\\s*x-scope\\s*"+f+"\\s*","g")," ")),k+=(k?" ":"")+"x-scope "+d,g!==k&&Ye(a,k));e||bg.store(c,b.D,h,b.v);return h};
m.za=function(a,b){var c=this.xa(a),e=X(c),d=e.D;c===this.J||d||(this.za(c,e),d=e.D);c=Object.create(d||null);d=Gf(a,b.A,b.cssBuild);a=Ef(e.A,a).C;Object.assign(c,d.qc,a,d.wc);this.Nb(c,b.R);a=Jf;e=Object.getOwnPropertyNames(c);d=0;for(var f;d<e.length;d++)f=e[d],c[f]=Cf(a,c[f],c);b.D=c};m.Nb=function(a,b){for(var c in b){var e=b[c];if(e||e===0)a[c]=e}};m.styleDocument=function(a){this.styleSubtree(this.J,a)};
m.styleSubtree=function(a,b){var c=Ze(a),e=c.shadowRoot,d=this.ua(a);(e||d)&&this.styleElement(a,b);if(a=d?c:e)for(a=Array.from(a.querySelectorAll("*")).filter(function(f){return Ze(f).shadowRoot}),b=0;b<a.length;b++)this.styleSubtree(a[b])};m.Xb=function(a){for(var b=0;b<a.length;b++){var c=this.h.getStyleForCustomStyle(a[b]);c&&this.Wb(c)}};m.ob=function(a){for(var b=0;b<a.length;b++){var c=this.h.getStyleForCustomStyle(a[b]);c&&If(c,this.B.D)}};
m.hb=function(a){var b=this,c=af(a);c!==this.B.cssBuild&&(this.B.cssBuild=c);if(!bf(c)){var e=Re(a);Qe(e,function(d){if(S)sf(d);else{var f=W;d.selector=d.parsedSelector;sf(d);f.Xa(d,f.cc)}T&&c===""&&(b.S(),b.m&&b.m.transformRule(d))});T?a.textContent=Pe(e):this.B.A.rules.push(e)}};m.Wb=function(a){if(T&&this.m){var b=Re(a);this.S();this.m.transformRules(b);a.textContent=Pe(b)}};
m.getComputedStyleValue=function(a,b){var c;T||(c=(X(a)||X(this.xa(a))).D[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};m.zc=function(a,b){var c=Ze(a).getRootNode();b=b?(typeof b==="string"?b:String(b)).split(/\s/):[];c=c.host&&c.host.localName;if(!c){var e=a.getAttribute("class");if(e){e=e.split(/\s/);for(var d=0;d<e.length;d++)if(e[d]===W.aa){c=e[d+1];break}}}c&&b.push(W.aa,c);T||(c=X(a))&&c.v&&b.push(Jf.kb,c.v);Ye(a,b.join(" "))};m.ac=function(a){return X(a)};
m.yc=function(a,b){W.element(a,b)};m.Cc=function(a,b){W.element(a,b,!0)};m.xc=function(a){return Rf(a)};m.mc=function(a){return Qf(a)};Y.prototype.flush=Y.prototype.flush;Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.zc;
Y.prototype._styleInfoForNode=Y.prototype.ac;Y.prototype.transformCustomStyleForDocument=Y.prototype.hb;Y.prototype.getStyleAst=Y.prototype.nc;Y.prototype.styleAstToString=Y.prototype.Ac;Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Y.prototype.scopeNode=Y.prototype.yc;Y.prototype.unscopeNode=Y.prototype.Cc;Y.prototype.scopeForNode=Y.prototype.xc;Y.prototype.currentScopeForNode=Y.prototype.mc;Y.prototype.prepareAdoptedCssText=Y.prototype.prepareAdoptedCssText;
Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return S}},nativeCss:{get:function(){return T}}});var Z=new Y,dg,eg;window.ShadyCSS&&(dg=window.ShadyCSS.ApplyShim,eg=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:T,nativeShadow:S,cssBuild:Ge,disableRuntime:He};dg&&(window.ShadyCSS.ApplyShim=dg);eg&&(window.ShadyCSS.CustomStyleInterface=eg);})();
//# sourceMappingURL=blaze-out/platform-66B4CEA8-opt/bin/third_party/javascript/polymer/v2/webcomponentsjs/webcomponents-sd-ce.js.sourcemap
