(function(){'use strict';var aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");},q=ba(this),ca=function(a,b){if(b)a:{var d=q;a=a.split(".");for(var c=
0;c<a.length-1;c++){var e=a[c];if(!(e in d))break a;d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&b!=null&&aa(d,a,{configurable:!0,writable:!0,value:b})}};ca("globalThis",function(a){return a||q});/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var r=globalThis.trustedTypes,t;function da(){var a=null;if(!r)return a;try{let b=d=>d;a=r.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var u=class{constructor(a){this.P=a}toString(){return this.P+""}};function v(a){var b;t===void 0&&(t=da());a=(b=t)?b.createScriptURL(a):a;return new u(a)}function y(a){if(a instanceof u)return a.P;throw Error("");};function z(a,...b){if(b.length===0)return v(a[0]);var d=a[0];for(let c=0;c<b.length;c++)d+=encodeURIComponent(b[c])+a[c+1];return v(d)}function A(a,b){a=y(a).toString();var d=a.split(/[?#]/),c=/[?]/.test(a)?"?"+d[1]:"";return ea(d[0],c,/[#]/.test(a)?"#"+(c?d[2]:d[1]):"",b)}
function ea(a,b,d,c){function e(g,h){g!=null&&(Array.isArray(g)?g.forEach(k=>e(k,h)):(b+=f+encodeURIComponent(h)+"="+encodeURIComponent(g),f="&"))}var f=b.length?"&":"?";c.constructor===Object&&(c=Object.entries(c));Array.isArray(c)?c.forEach(g=>e(g[1],g[0])):c.forEach(e);return v(a+b+d)}var fa=/[^#]*/;function ha(a){a=y(a).toString();return v(fa.exec(a)[0]+"")};function B(a){return a.endsWith("/")?a.slice(0,-1):a}z`cs/ta/tag_assistant_api_bin.js`;var ia=z`cs/ta/content_script_bin.js`,ja=z`cs/ta/start_debug_content_script_bin.js`,C=z`cs/ta/start_prod_debug_content_script_bin.js`,ka=z`cs/gf/guided_flows_content_script_bin.js`,D=B("https://tagassistant.google.com/guided_flows/open"),E=B("https://tagassistant.google.com");B("https://tagassistant.google.com/embedded/side_panel");function F(a){try{return JSON.parse(atob(a))}catch(b){}}async function la(a){try{let b=await a.i18n.getUILanguage();if(b)return b}catch(b){}}function ma(a){if(!a)return!1;try{switch(JSON.parse(atob(a)).purpose){case "guided_flows_install_ta":case "guided_flow_ads_conversion_setup":return!0;default:return!1}}catch(b){return!1}};function na(a){a:{var b=a.type;if(typeof b!=="string")b=!1;else switch(b){case "CLEAR_COOKIE":case "CONTAINER_DETAILS":case "CONTAINER_STARTING":case "LEGACY_CONTAINER_STARTING":case "MEMO":case "END_SESSION":case "PING":case "DEBUG_CONTAINER_FAILED_TO_LOAD":case "NAVIGATE":case "RESEND_MEMOS":case "PAGE_SUMMARY":case "SIDE_PANEL":case "CONNECTION_ISSUE":case "PASSTHROUGH_API":b=!0;break a;default:b=!1}}return b&&a.type==="SIDE_PANEL"};var oa=async function(a){if(a.g.management&&a.g.runtime.id!=="kejbdjndbnbjgmefkgdddjlbokphdefk")try{await a.g.management.get("kejbdjndbnbjgmefkgdddjlbokphdefk")&&await a.g.management.uninstallSelf()}catch(b){}},G=function(a){a.j&&a.g.tabs.get(a.j,b=>{b!=null&&b.windowId&&a.g.windows.update(b.windowId,{focused:!0},()=>{a.g.tabs.update(a.j,{active:!0})})})},pa=function(a){a.g.tabs.query({url:"https://*.google.com/embed/tagging/info/sidepanel*"},b=>{for(let d of b)d.id&&a.g.scripting.executeScript({target:{tabId:d.id},
files:["cms/sidepanel/open_side_panel_content_script_compiled.js"]})})},qa=async function(a){var [b]=await a.g.tabs.query({active:!0,lastFocusedWindow:!0});if(b==null?0:b.id)a.j=b.id},ra=function(a){var b=H(a.l),d=new URL(b?D:a.H);d.searchParams.set("opened","true");if(b&&a.l){let c=F(a.l);d.searchParams.set("context",a.l);(c==null?0:c.authuser)&&d.searchParams.set("authuser",c.authuser)}a.g.tabs.create({url:d.toString(),active:!0},c=>{c.id&&a.u(c.id,c,b)})},sa=async function(a,b){var d=I;if(d.j&&
d.j===b){var c=a.data,e;switch((e=a.data)==null?void 0:e.type){case "MEMO":let f,g,h;c=c==null?void 0:(f=c.data)==null?void 0:(g=f.memo)==null?void 0:(h=g.sanitized)==null?void 0:h.messageType;if(c!=="INIT"&&c!=="GTAG_HIT")return;break;default:return}try{await d.g.runtime.sendMessage({type:"onMemoMessage",data:Object.assign({},a,{tabId:b})})}catch(f){}}},ua=class{constructor(){this.g=chrome;this.enableSidePanel=!0;this.H="https://support.google.com/embed/tagging/info/sidepanel";this.T=!1;this.j=this.v=
0;this.J=!1;oa(this);this.setup()}setup(){this.enableSidePanel&&(this.g.runtime.onMessage.addListener((a,b,d)=>{switch(a.type){case "open_side_panel":let c;(a=(c=b.tab)==null?void 0:c.id)&&b.url&&(b.url.startsWith(this.H)||ta.test(b.url))&&!this.j?this.u(a,b.tab,H(this.l)):G(this);break;case "open_ta_side_panel":if(!b.tab)break;let e;(e=this.R)==null||e.call(this,b.tab);break;case "side_panel_context":d({type:"side_panel_context",context:this.l});break;case "start_prod_debug_api":let f;(f=this.B)==
null||f.call(this,a.tabId);break;case "end_prod_debug_api":let g;(g=this.B)==null||g.call(this,a.tabId,!0);break;case "close_side_panel":this.j&&this.g.sidePanel.setOptions({tabId:this.j,enabled:!1})}}),this.g.runtime.onInstalled.addListener(a=>{a.reason===this.g.runtime.OnInstalledReason.INSTALL&&this.g.tabs.query({active:!0,lastFocusedWindow:!0},([b])=>{var d=b==null?void 0:b.url,c;if(c=d)if(this.T)c=!0;else{c=new URL(d);var e=RegExp("chrome-extension:\\/\\/([^\\/]+)"),f;e=(f=this.g.runtime.getURL("/").match(e))==
null?void 0:f[1];c=d.startsWith("https://chromewebstore.google.com/detail")&&!!e&&c.pathname.endsWith(e)&&c.searchParams.get("side_panel")==="true"}if(c){if(d=(new URL(d)).searchParams.get("context"))this.l=d;d=H(this.l);f=new URL(d?D:this.H);f.searchParams.set("installed","true");this.l&&f.searchParams.set("context",this.l);d&&(b==null?0:b.id)?this.g.tabs.update(b.id,{url:f.toString(),active:!0}):this.g.tabs.create({url:f.toString(),active:!0})}});pa(this)}),this.g.runtime.onConnect.addListener(a=>
{a.name==="sidePanel"&&(this.j||(this.A(),qa(this)),a.onMessage.addListener(b=>{this.v||b.type!=="connect_side_panel"||(this.v=setTimeout(()=>{this.v=0;a.postMessage({type:"side_panel_connected"})},25E3))}),a.onDisconnect.addListener(()=>{this.F();this.j=0;this.l=void 0;this.v&&clearTimeout(this.v);var b;(b=this.B)==null||b.call(this,0,!0)}))}),this.g.runtime.onMessageExternal.addListener((a,b,d)=>{switch(a==null?void 0:a.type){case "connect_side_panel":d({type:"side_panel_connected"});break;case "open_side_panel":if(this.j){G(this);
break}a.context&&(this.l=a.context);let c;a.openInSameTab&&(b==null?0:(c=b.tab)==null?0:c.id)?this.u(b.tab.id,b.tab,H(this.l)):ra(this);break;case "close_side_panel":this.j&&this.g.sidePanel.setOptions({tabId:this.j,enabled:!1})}}))}u(a,b,d){this.A();if(d){if(b){this.j=a;let c;(c=this.R)==null||c.call(this,b,!0)}}else this.g.sidePanel.setOptions({enabled:!0,tabId:a,path:`cms/sidepanel/sidepanel.html?time=${Date.now()}`}),this.g.sidePanel.open({tabId:a},()=>{this.j=a})}A(){this.J||(this.J=!0,this.g.scripting.registerContentScripts([{id:"ct-sidepanel",
matches:["<all_urls>"],js:J,runAt:"document_start",allFrames:!0}]),this.l&&this.g.tabs.query({currentWindow:!0},a=>{for(let b of a){let d;b.id&&((d=b.url)==null?0:d.startsWith("http"))&&this.g.scripting.executeScript({target:{allFrames:!0,tabId:b.id},files:J})}}))}F(){this.g.scripting.unregisterContentScripts({ids:["ct-sidepanel"]});this.J=!1}},J=["cms/polyfills/webcomponents-ce.js",ka.toString()],ta=RegExp("https?://[^/:]*\\.google\\.com(:\\d+)?/guided_flows/open*");
function H(a){if(!a)return!1;try{let d=JSON.parse(atob(a));a:if(d)switch(d.purpose){case "guided_flows_install_ta":case "guided_flow_ads_conversion_setup":var b=!0;break a;default:b=!1}else b=!1;return b}catch(d){return!1}};async function va(a){try{return(await fetch(a,{method:"HEAD",mode:"no-cors",cache:"no-store"})).status<400}catch(b){return!1}};var K=Array.from("\ud83d\udd37\ud83d\udfe1\ud83d\udfea\ud83d\udfe9\ud83d\udd35\ud83d\udd36\ud83d\udfe2\ud83d\udfe3\ud83d\udfe6\ud83d\udfe8"),wa=function(a){a.g.action.onClicked.addListener(b=>{a.u(b)})},ya=function(a){if(a.g.runtime.id!=="kejbdjndbnbjgmefkgdddjlbokphdefk"){var b=a.g.runtime.getManifest().version;setTimeout(()=>{a.g.runtime.onUpdateAvailable.addListener(d=>{xa(a,d,b)})},2E3)}},za=async function(a){await L(a,"ta_content_script",ia.toString())},M=function(a,b,d,c,e){var f=b.frames.get(d);
f==null&&(e!=null?a=e:(f=K[a.D],a.D++,a.D>=K.length&&(a.D=0),a=f),f={port:c,emoji:a},b.frames.set(d,f));c!=null&&(f.port=c);e!=null&&(f.emoji=e);return f},Q=function(a,b,d={}){var c=a.h.get(b);if(c==null){c={o:new Set};var e;if(!(e=a.h.size===0))a:{for(let [f]of a.h)if(!a.i.has(f)){e=!1;break a}e=!0}e&&(N(a),d.C&&a.A());a.h.set(b,c);O(a);P(a,b)}return c},T=function(a,b,d,c,e,f){e.o.add(b);(e=a.i.get(b))?R(e,c):(e=S(c,d),b===c&&(e.m=0),a.i.set(b,e),Aa(a,b,d));e.U=!!f;return e},Ca=function(a,b,d){var c,
e,f=d!=null?d:(c=b.sender)==null?void 0:(e=c.tab)==null?void 0:e.id;if(f!=null){console.log("Got connection from Tag Assistant on tab %s \n",f);P(a,f);var g=b.name==="TA_EXT_PORT_SIDE_PANEL",h=Q(a,f,{C:!g});h.port=b;var k;h.url=(k=b.sender)==null?void 0:k.url;c=a.getContext(h.url);if(h.K&&!ma(c)){let l=h.K;setTimeout(()=>{U(a,l)},300);h.K=void 0}b.onMessage.addListener(l=>{a.h.has(f)||(a.h.size===0&&(N(a),g||a.A()),a.h.set(f,h),O(a),P(a,f));if(na(l.data)){var n=!1;switch(l.data.subType){case "sp_open_ta":Ba(a,
f);n=!0;break;case "sp_guided_install":n=btoa(JSON.stringify({entryPoint:"ta_side_panel"}));var m,p;(p=a.S)==null||p.call(a,f,(m=b.sender)==null?void 0:m.tab,n);n=!0}if(n)return}l.data.type==="CONTAINER_DETAILS"?(m=l.data.data.nonce,p=a.G.get(m),a.G.delete(m),V(l,p)):h.o.forEach(w=>{W(a,w,l,g)})});b.onDisconnect.addListener(()=>{h.port===b&&(console.log("port to Tag Assistant tab %s closed",f),h.port=void 0);var l=a.i.get(f);!l||d&&!l.tagAssistantTabIds.includes(d)||(X(l,f),d&&(W(a,f,{type:"PIPE_MESSAGE",
origin:"*",dId:"",tId:0,source:"EXTENSION",data:{type:"SIDE_PANEL",subType:"sp_off",uId:""}},!0),a.h.delete(f),a.h.size===0&&L(a,"ta_prod_debug_attribute_content_script",C.toString(),[0])))})}},Ea=async function(a,b){try{var d;let e;var c=new URL((e=(d=b.sender)==null?void 0:d.url)!=null?e:"")}catch(e){console.log("=== onTagAssistantSidePanelConnect invalid url");console.log(e);return}d=Number(c.searchParams.get("tabId"));!isNaN(d)&&d&&(console.log("Got connection from sidePanel Tag Assistant on tab %s \n",
d),Ca(a,b,d),b=a.h.get(d),T(a,d,c.toString(),d,b).I=1,Da(a,d))},Fa=function(a,b){var d,c,e=(d=b.sender)==null?void 0:(c=d.tab)==null?void 0:c.id,f;d=(f=b.sender)==null?void 0:f.frameId;if(e!=null&&d!=null){P(a,e);var g=a.i.get(e);g==null&&(g=S(),g.m=0,a.i.set(e,g));var h=M(a,g,d,b);b.onMessage.addListener(k=>{a.N.forEach(m=>{m(k,e)});if(g.tagAssistantTabIds.length){var l=k.data.type;l==="CONTAINER_STARTING"&&a.G.set(k.data.data.nonce,h);k.data.emoji=h.emoji;k.source="EXTENSION";k.data.uniqueId=g.uniqueId;
k.data.uId=`${g.uniqueId}|${k.dId}`;if(l==="PAGE_SUMMARY")var n=k.data.data.groupId;else l==="MEMO"&&(n=k.data.data.memo.sanitized.key.groupId);if(n&&g.uniqueId){if((l=a.M[n])&&l!==g.uniqueId)return;a.M[n]=g.uniqueId}n=new Set;for(let m of g.tagAssistantTabIds)l=a.h.get(m),(l==null?0:l.port)&&n.add(l.port);for(let m of n)m.postMessage(k)}});b.onDisconnect.addListener(()=>{h.port===b&&(h.port=void 0)})}},Ha=function(a,b,d,c,e,f){if(Ga(c))return!0;d=(e==null?0:e.length)?e[0]:d;e=a.h.get(d);if(e==null||
!e.port)return!1;T(a,b,c,d,e,f);return!0},V=function(a,b){b!=null&&b.port&&(a.data.emoji=b.emoji,a.source="EXTENSION",b.port.postMessage(a))},Ia=function(a,b,d){for(let c of a.h.values())if(c.o.has(b)){let e;(e=c.port)==null||e.postMessage(d)}},Ja=function(a,b,d){var c=a.i.get(b);c||(c=S(void 0,d),c.m=0,a.i.set(b,c));return c},Ka=function(a,b,d=!1){if(b.id!=null){var c=void 0;b.url&&(c=new URL(b.url),c=encodeURIComponent(c.href));c=new Map([["tabId",`${b.id}`],["url",c]]);d&&c.set("flowType","guidedFlows");
var e;if(d=(e=a.L)==null?void 0:e.call(a))if(e=F(d))e.authuser&&c.set("authuser",e.authuser),c.set("context",d);e=A(z`ta_side_panel/index.html`,c);a.g.sidePanel.setOptions({enabled:!0,tabId:b.id,path:e.toString()});a.g.sidePanel.open({tabId:b.id},()=>{})}},P=function(a,b){a.g.tabs.update(b,{autoDiscardable:!1})},U=async function(a,b){await a.g.tabs.reload(b,{bypassCache:!0})},N=function(a){a.O==null&&(a.O=setInterval(()=>{a.g.runtime.getManifest()},15E3))},O=function(a){a.g.storage.local.set({lastTaConnectedTimestamp:Date.now()})},
Ba=async function(a,b){var d=a.i.get(b);if(d){d.m=2;var c=d.tagAssistantTabIds.filter(l=>l!==b)[0];if(c)try{var e=await a.g.tabs.get(c);if(e&&e.id){await a.g.windows.update(e.windowId,{focused:!0});await a.g.tabs.update(e.id,{active:!0});await U(a,b);return}}catch(l){}c=await a.g.tabs.get(b);e=c.index;var f=c.windowId,g=c.url,h=v(E);g=new Map([["restart_tag_assistant","1"],["utm_source","sp_new_tab"],["tabId",`${b}`],["sp_origin",g?`${(new URL(g)).origin}`:""],["extensionId",a.g.runtime.id]]);var k=
await la(a.g);k&&g.set("hl",k);h=ha(A(h,g));c=await a.g.tabs.create({url:h.toString(),active:!0,index:e,windowId:f,openerTabId:c.id});c.id&&(a=Q(a,c.id,{C:!0}),a.K=b,a.o.add(b),R(d,c.id))}},W=function(a,b,d,c){if(a=a.i.get(b))d.data.type==="CLEAR_COOKIE"?a.m=0:a.m!==0||c||(a.m=1),a.frames.forEach(e=>{V(d,e)})},L=async function(a,b,d,c=[0,1],e){var f=!0;(await a.g.scripting.getRegisteredContentScripts({ids:[b]})).length!==0&&(c.includes(0)?await a.g.scripting.unregisterContentScripts({ids:[b]}):c.includes(1)&&
(f=!1));f&&c.includes(1)&&await a.g.scripting.registerContentScripts([{id:b,allFrames:!0,js:[d],matches:["<all_urls>"],excludeMatches:"*://www.googletagmanager.com/static/service_worker/* *://googletagmanager.com/static/service_worker/* *://tagassistant.google.com/ *://tagassistant.google.com/* *://td.doubleclick.net/* *://*.fls.doubleclick.net/*".split(" "),runAt:"document_start"}]);e==null||e()},Da=function(a,b){L(a,"ta_prod_debug_attribute_content_script",C.toString(),[1],()=>{U(a,b)})},Aa=async function(a,
b,d){if(!await va(d)){var c=a.i.get(b),e;Ia(a,b,{type:"PIPE_MESSAGE",source:"EXTENSION",origin:"*",tId:b,dId:(e=c==null?void 0:c.parentDocumentId)!=null?e:"",data:{type:"CONNECTION_ISSUE",data:{issues:[{type:7}],pageUrl:d},uniqueId:c==null?void 0:c.uniqueId,uId:""}})}},xa=async function(a,b,d){b.version!==d&&await La(a)&&a.g.runtime.reload()},La=async function(a){if(a.h.size)return!1;a=await a.g.storage.local.get(["lastTaConnectedTimestamp"]);var b;a=Number((b=a.lastTaConnectedTimestamp)!=null?b:
0);return!a||Number.isNaN(a)||Date.now()-a>18E5?!0:!1},Ma=class{constructor(){this.g=chrome;this.h=new Map;this.i=new Map;this.D=0;this.M={};this.G=new Map;this.N=[];wa(this);ya(this);this.F();za(this);this.g.runtime.onMessage.addListener((a,b,d)=>{var c;if(!(b==null?0:(c=b.tab)==null?0:c.id)){let f;(b==null?0:(f=b.origin)==null?0:f.includes("google.com"))&&b.origin.includes("tagassistant")&&d(void 0)}else if(a.type==="CHECK_DEBUG"){c=this.i.get(b.tab.id);let f;var e=Object.assign({},a,{source:"EXTENSION",
startDebug:!1,startProdDebug:!1,tabId:b.tab.id,topDocumentId:(f=c==null?void 0:c.parentDocumentId)!=null?f:""});c&&(e.startDebug=Y(c.m),a=!a.referrer&&Ga(b.url),!c.U&&a&&c.m!==2&&(e.startDebug=!1,c.m=0),e.startProdDebug=Y(c.I));e.tagAssistantTabIds=c==null?void 0:c.tagAssistantTabIds;c!=null&&c.tagAssistantTabIds.length&&b&&b.frameId!=null&&(b=M(this,c,b.frameId),e.emoji=b.emoji);d(e)}else if(a.type==="RECONNECT")for(e of a.tagAssistantTabIds)d=Q(this,e,{C:!0}),d=T(this,b.tab.id,b.tab.url||b.tab.pendingUrl||
"",e,d),(b==null?void 0:b.frameId)!=null&&a.emoji&&M(this,d,b==null?void 0:b.frameId,void 0,a.emoji)});this.g.runtime.onConnectExternal.addListener(a=>{var b,d=(b=a.sender)==null?void 0:b.origin;if(d){b=!1;if(d==="https://tagassistant.google.com"||d.startsWith("https://")&&d.endsWith(".corp.google.com"))b=!0;b&&(a.name==="TAG_ASSISTANT_EXTENSION_PORT"&&Ca(this,a),a.name==="TA_EXT_PORT_SIDE_PANEL"&&Ea(this,a))}});this.g.runtime.onConnect.addListener(a=>{Fa(this,a)});this.g.webNavigation.onCreatedNavigationTarget.addListener(({tabId:a,
sourceTabId:b,url:d})=>{var c=new URL(d);c.hostname.endsWith(".google.com")&&c.searchParams.get("restart_tag_assistant")!=null?(this.h.has(b)||((c=this.i.get(b))?(R(c,a),c.m=1):this.i.set(b,S(a,d)),Q(this,a,{C:!0}).o.add(b)),c=!0):c=!1;c||Ha(this,a,b,d)||(c=this.i.get(b),c!=null&&c.tagAssistantTabIds.length&&Y(c.m)&&Ha(this,a,b,d,c.tagAssistantTabIds,!0))});this.g.tabs.onUpdated.addListener((a,b,d)=>{if(a=this.i.get(a))a.url=d.url});this.g.tabs.onRemoved.addListener(a=>{var b=this.h.get(a);if(b){this.h.delete(a);
for(var d of b.o){let f=this.i.get(d);if(f)for(let g of f.frames.values()){let h;V({type:"PIPE_MESSAGE",source:"EXTENSION",origin:b.url?(new URL(b.url)).origin:"*",tId:a,dId:(h=f==null?void 0:f.parentDocumentId)!=null?h:"",data:{type:"CONNECTION_ISSUE",data:{issues:[{type:1}],pageUrl:f.url||""},uId:""}},g)}f&&(f.m=0,X(f,a))}this.h.size===0&&(clearInterval(this.O),this.F())}b=this.i.get(a);this.i.delete(a);d=!1;for(let f of this.h.values())if(f.o.has(a)){var c=f;d=f.o.size===1;break}if(c){var e;Ia(this,
a,{type:"PIPE_MESSAGE",source:"EXTENSION",origin:"*",tId:a,dId:(e=b==null?void 0:b.parentDocumentId)!=null?e:"",data:{type:"CONNECTION_ISSUE",data:{issues:[{type:2,allDebugTabsClosed:d}],pageUrl:(b==null?void 0:b.url)||""},uId:""}});c.o.delete(a)}});this.g.webNavigation.onCommitted.addListener(({tabId:a,frameId:b,url:d,documentId:c})=>{var e=new URL(d),f=e.origin===E,g=Number(e.searchParams.get("tabId")),h=this.h.has(g);if(e.pathname==="/login/success"&&h&&f){let l;b=(l=e.searchParams.get("authuser"))!=
null?l:"0";this.g.tabs.remove(a,()=>{});let n=new Map([["tabId",`${g}`],["authuser",`${b}`],["isPostLogin","true"],["rand",`${Math.floor(Math.random()*1E4)}`]]);var k;if(a=(k=this.L)==null?void 0:k.call(this))if(a=F(a))a.authuser=b,n.set("context",btoa(JSON.stringify(a)));this.g.sidePanel.getOptions({tabId:g}).then(m=>{var p="",w="";if(m.path){m=this.g.runtime.getURL(m.path);m=new URL(m);if(m.searchParams.has("flowType")){let x;p=(x=m.searchParams.get("flowType"))!=null?x:""}if(m.searchParams.has("context")){let x;
w=(x=m.searchParams.get("context"))!=null?x:""}}p&&n.set("flowType",p);w&&n.set("context",w);p=A(z`ta_side_panel/index.html`,n);this.g.sidePanel.setOptions({enabled:!0,tabId:g,path:p.toString()})})}else e.origin!=="https://tagassistant.google.com"&&(k=Ja(this,a,d),c&&d.startsWith("http")&&b===0&&(k.parentDocumentId=c),b===0&&(a=this.h.get(a),k&&a&&(k.uniqueId=k.uniqueId==null?1:++k.uniqueId)))});this.g.runtime.onMessageExternal.addListener((a,b,d)=>{switch(a==null?void 0:a.type){case "open_side_panel":case "connect_side_panel":case "side_panel_connected":case "side_panel_context":case "list_tags":case "list_tags_off":case "open_ta_side_panel":case "start_prod_debug_api":case "end_prod_debug_api":case "close_side_panel":break;
default:d({})}})}getContext(a){if(!a)return null;try{return(new URL(a)).searchParams.get("context")}catch(b){return null}}async A(){await L(this,"ta_debug_attribute_content_script",ja.toString())}async F(){(await this.g.scripting.getRegisteredContentScripts({ids:["ta_debug_attribute_content_script"]})).length!==0&&await this.g.scripting.unregisterContentScripts({ids:["ta_debug_attribute_content_script"]})}u(a,b){Ka(this,a,b)}B(a,b){if(b)this.h.size===0&&L(this,"ta_prod_debug_attribute_content_script",
C.toString(),[0]);else if(b=this.i.get(a))b.I=1,Da(this,a)}};function S(a,b){return{tagAssistantTabIds:a?[a]:[],frames:new Map,m:1,I:0,url:b}}function R(a,b){a.tagAssistantTabIds.includes(b)||a.tagAssistantTabIds.push(b)}function X(a,b){a.tagAssistantTabIds=a.tagAssistantTabIds.filter(d=>d!==b)}function Y(a){switch(a){case 1:case 2:return!0;case 0:return!1;default:return!1}}var Na=["support","developers","tagmanager"];
function Ga(a){if(!a)return!1;try{let b=new URL(a);return b.host.match(/\.?google.co(m|(\.[a-z]{2}))/)||b.host.match(/\.?youtube.co(m|(\.[a-z]{2}))/)?Na.includes(b.host.split(".")[0]):!1}catch(b){return!1}};self.oninstall=()=>self.skipWaiting();var Z=new Ma,I=new ua;Z.S=(a,b,d)=>{var c=I;c.j?G(c):(c.l=d,c.u(a,b,H(d)))};Z.N.push((a,b)=>{sa(a,b)});I.R=(a,b)=>{Z.u(a,b)};I.B=(a,b)=>{Z.B(a,b)};Z.L=()=>I.l;}).call(this);
